### ISSUE TITLE
BUG: Rocksdb options not changed even if update in Pegasus config file

### ISSUE THREAD

**Issue by acelyc111** [apache/incubator-pegasus#1025]
Because we will load rocksdb options from disk when bootstrap, even if we update configs in Pegasus' config file, it seems will not take effect on these options.

**Comment by WHBANG** [comment]
i mark

**Comment by acelyc111** [comment]
> 

Thanks!

**Comment by acelyc111** [comment]
> i mark

@WHBANG Thanks!
