### ISSUE TITLE
Feature: Integrate with Apache Ranger

### ISSUE THREAD

**Issue by acelyc111** [apache/incubator-pegasus#1054]
Apache Ranger™ [1] is a framework to enable, monitor and manage comprehensive data security across the Hadoop platform. There are many big data components support to integate with Ranger, like HDFS，HBase，Hive，Yarn，Kafka，Kudu.

Now Pegasus supports Kerberos and built-in ACL, but it's a bit of difficult to manage it, we can make Pegasus interact with Ranger to make it easier for management.

1. https://ranger.apache.org/

**Comment by acelyc111** [comment]
It is also tracked in Ranger community https://issues.apache.org/jira/browse/RANGER-3831

**Comment by kirbyzhou** [comment]
If I understand it correctly, the ACL model is so simple now. There are two access_controller class.  

- meta_access_controller:

Super User is allowed to do anything. 
All other users are allowed to do the things listed in FLAGS_meta_acl_rpc_allow_list. There is no per-user settings.
Default meta_acl_rpc_allow_list are 
```
RPC_CM_LIST_APPS 
RPC_CM_LIST_NODES 
RPC_CM_CLUSTER_INFO 
RPC_CM_QUERY_PARTITION_CONFIG_BY_INDEX
```

- replica_access_controller： 

Super User is allowed to do anything. 
Users in the users list are allowed to do anything. Users are set by 'replica_access_controller.allowed_users' vars in replica::update_ac_allowed_users
There seems no per-user settings too.


It seems we first have to enhance the access controller mech, add per-user / per-table support.
Such as :
{ Table1: { user1: read, user2: read+write }, Table2: { user3: read, user4: read+write } }

**Comment by kirbyzhou** [comment]
Add a draft of Ranger Service definition
[here](https://issues.apache.org/jira/secure/attachment/13047331/ranger-servicedef-pegasus.json)

**Comment by acelyc111** [comment]
The current ACL is described in https://github.com/apache/incubator-pegasus/issues/170 and [Pegasus 安全认证](https://mp.weixin.qq.com/s?__biz=MzkzNzAzNDgyNg==&mid=2247483801&idx=1&sn=0516fcdfb3667b85d03eb5a40293e6de&chksm=c294d4bcf5e35daa67a4eb3317749c7a643e09a54c5c886be407a1105d96c6607c416cb4310c&token=1577740624&lang=en_US#rd)

It can be summarized as following:


operation \ user | super user | table owner | other users
-- | -- | -- | --
query cluster basic info | √ | √ | √
table read and write | √ | √ | ×
cluster control | √ | × | ×

The extended ACL is based on the former design and detailed as following:
 


operation \ details | ACL symbol | rpc code | resource example | --
-- | -- | -- | -- | --
Global level | -- | -- | -- |  
query cluster,server | metadata | cluster：<br>RPC_CM_LIST_NODES<br>RPC_CM_CLUSTER_INFO<br>RPC_CM_LIST_APPS（can query all tables）<br>server：<br>RPC_QUERY_DISK_INFO |   | 
control cluster,server,multi tables | control | cluster+server：<br>RPC_HTTP_SERVICE（http request，has no principal currently）<br>set LB level：<br>RPC_CM_CONTROL_META<br>recover meta server though replica servers：<br>RPC_CM_START_RECOVERY<br>on replica server: migrate replica between disks：<br>RPC_REPLICA_DISK_MIGRATE<br>on replica server:<br>add new disks:<br>RPC_ADD_NEW_DISK<br>on replica server:<br>detect hot key:<br>RPC_DETECT_HOTKEY<br>cluster+server: remote command(include many operations):<br>RPC_CLI_CLI_CALL<br>(multi-tables)backup policy's add,modify(maybe removed later):<br>RPC_CM_ADD_BACKUP_POLICY<br>RPC_CM_MODIFY_BACKUP_POLICY | -- | --
Database级别权限* | -- | -- | -- | --
查看集群/server | list | 集群：RPC_CM_LIST_APPS（只能查询到有权限的db下的表） | -- | --
创建表格 | create | RPC_CM_CREATE_APP | db1 | 可创建db1_*开头的表格
删除/召回 表格 | drop | RPC_CM_DROP_APPRPC_CM_RECALL_APP | -- | --
管理表格-查看 | metadata | (多表)备份policy的查询（后续会删除，也有可替代方法，设计上直接禁用）：RPC_CM_QUERY_BACKUP_POLICY(单表)表级backup的查询：RPC_CM_QUERY_BACKUP_STATUS(单表)从backup恢复表的查询：RPC_CM_QUERY_RESTORE_STATUS(单表)热备份的查询：RPC_CM_QUERY_DUPLICATION(单表)partition split的查询：RPC_CM_QUERY_PARTITION_SPLIT(单表)bulk load的查询：RPC_CM_QUERY_BULK_LOAD_STATUS(单表)manual compact的查询：RPC_CM_QUERY_MANUAL_COMPACT_STATUS(单表)表副本数的查询：RPC_CM_GET_MAX_REPLICA_COUNT | -- | --
管理表格-控制 | control | (单表)backup的开始：RPC_CM_START_BACKUP_APP(单表)从backup恢复表的控制：RPC_CM_START_RESTORE(单表)做一个分片的迁移：RPC_CM_PROPOSE_BALANCER(单表)热备份的添加、修改：RPC_CM_ADD_DUPLICATIONRPC_CM_MODIFY_DUPLICATION(单表)更新表的env：RPC_CM_UPDATE_APP_ENV(单表)表的DDD诊断（故障恢复）：RPC_CM_DDD_DIAGNOSE(单表)partition split的开始、控制：RPC_CM_START_PARTITION_SPLITRPC_CM_CONTROL_PARTITION_SPLIT(单表)bulk load的开始、控制、清理：RPC_CM_START_BULK_LOADRPC_CM_CONTROL_BULK_LOADRPC_CM_CLEAR_BULK_LOAD(单表)manual compact的开始：RPC_CM_START_MANUAL_COMPACT(单表)表副本数的修改：RPC_CM_SET_MAX_REPLICA_COUNT | -- | --
Database/Table级别权限 | -- | -- | -- | --
表读 | read | meta server：路由信息：RPC_CM_QUERY_PARTITION_CONFIG_BY_INDEXlist：RPC_CM_LIST_APPS（只能查询到有权限的表）replica server：server级：replica_stub::on_client_readreplica级：replica::on_client_read | db1/table1 | 可读db1_table1这张表
表写 | write | replica server：server级：replica_stub::on_client_writereplica级：replica::on_client_write | db1/* | 可写db1_*的表格
server 内部的（不做控制） | N/A | RPC_CM_CONFIG_SYNCRPC_CM_UPDATE_PARTITION_CONFIGURATIONRPC_CM_REPORT_RESTORE_STATUSRPC_CM_DUPLICATION_SYNCRPC_CM_REGISTER_CHILD_REPLICARPC_CM_NOTIFY_STOP_SPLITRPC_CM_QUERY_CHILD_STATERPC_NEGOTIATIONRPC_CALL_RAW_MESSAGERPC_CALL_RAW_SESSION_DISCONNECTRPC_NFS_GET_FILE_SIZERPC_NFS_COPYRPC_FD_FAILURE_DETECTOR_PINGRPC_CALL_RAW_MESSAGERPC_CALL_RAW_SESSION_DISCONNECTRPC_CONFIG_PROPOSALRPC_GROUP_CHECKRPC_QUERY_PN_DECREE（？）RPC_QUERY_REPLICA_INFORPC_QUERY_LAST_CHECKPOINT_INFORPC_PREPARERPC_GROUP_CHECKRPC_QUERY_APP_INFORPC_LEARNRPC_LEARN_COMPLETION_NOTIFYRPC_LEARN_ADD_LEARNERRPC_REMOVE_REPLICARPC_COLD_BACKUPRPC_CLEAR_COLD_BACKUPRPC_SPLIT_NOTIFY_CATCH_UPRPC_SPLIT_UPDATE_CHILD_PARTITION_COUNTRPC_BULK_LOADRPC_GROUP_BULK_LOAD | -- | --

**Comment by acelyc111** [comment]
1. More restrict for common query type requests.
  a. As table above, users should be granted 'metadata' before query cluster info.
2. MetaServer have to support table level ACL
  a. For example, query route info of a table (i.e. RPC_CM_QUERY_PARTITION_CONFIG_BY_INDEX)  must be in ACL
3. To support 'database' level ACL:
  a. on MetaServer:
    i. Handle requests on MetaServer, they are listed in the table above, 'Database level.list/create/drop/metadata/control'.
   ii. Add unordered_map<'table_prefix', unordered_set<user_name>> structure.
  iii. Parse table name from request messages when handle requests.
  a. on ReplicaServer:
    i. Add unordered_map<'table_prefix', unordered_set<user_name>> structure too.
   ii. Because "table prefix" string doesn't belong to any tables/replica, so besides replica envs, we have to add an extra server level envs for ACL.
  iii. We have to maintainance the relationship between table id and table name carefully.
   iv. Parse table id and transfer it to table name from request messages when handle requests.

**Comment by kirbyzhou** [comment]
We have finished the service definition in ranger according to this draft.
See https://issues.apache.org/jira/browse/RANGER-3831

**Comment by WHBANG** [comment]
Introduce the implementation and how to use:

1. The class diagram
![image](https://user-images.githubusercontent.com/38547944/218993763-91a7072b-086b-44fa-9041-636c5ea1d089.png)


First, you need to add ACL related configurations. The client configuration has not changed, the server has added new configurations:
```
enable_ranger_acl: indicates whether to use ranger for acl
ranger_service_url： ranger server url
ranger_service_name: use ranger policy name
mandatory_enable_acl: mandatory use range policy, currently used for testing
```
The details are as follows:
```
server
[security]
  update_ranger_policy_interval_sec
[ranger]
  ranger_service_url
  ranger_service_name
  ranger_legacy_table_database_mapping_rule
  mandatory_enable_acl
[security]
  enable_auth = true
  krb5_keytab = /root/apache/pegasus.keytab
  krb5_config = /etc/krb5.conf
  krb5_principal = XXXXX
  sasl_plugin_path = /root/apache/incubator-pegasus/thirdparty/output/lib/sasl2
  service_fqdn = XXXXX
  service_name = XXXXX
  mandatory_auth = true
  enable_acl = true
  super_users =
  meta_acl_rpc_allow_list =
  enable_ranger_acl = true
```
```
java client
java
meta_servers = 127.0.0.1:34601,127.0.0.1:34602,127.0.0.1:34603
operation_timeout = 5000
async_workers = 4
enable_perf_counter = false
perf_counter_tags = cluster=onebox,app=unit_test
push_counter_interval_secs = 10
meta_query_timeout = 5000
auth_protocol = kerberos
kerberos_service_name = XXXXX
kerberos_service_fqdn = XXXXX
kerberos_keytab = /root/apache/pegasus.keytab
kerberos_principal = XXXXX
```
```
shell
[security]
  enable_auth = true
  krb5_keytab = /root/apache/pegasus.keytab
  krb5_config = /etc/krb5.conf
  krb5_principal = XXXXX
  sasl_plugin_path = /root/apache/incubator-pegasus/thirdparty/output/lib/sasl2
  service_fqdn = XXXXX
  service_name = XXXXX
```
Second compatibility:
Retained the old ACL mode
1. Use the old ACL
```
enable_acl = true
enable_ranger_acl = false
```
2. user ranger for ACL
```
enable_acl = true
enable_ranger_acl = true
```

3. Third, define the ranger policy

- Pegasus resources can be divided into multiple types, and the operation types of each resource can also be divided. One operation type corresponds to one ACL symbol
<img width="773" alt="image" src="https://user-images.githubusercontent.com/38547944/204430376-17e8ae9a-bdac-466c-a2a7-d4f27cae09e0.png">

- ACLs on each type of resource correspond to specific rpc_code

<img width="646" alt="image" src="https://user-images.githubusercontent.com/38547944/204430797-5b45e079-84c5-4f3e-a470-db063d6d87d5.png">
<img width="846" alt="image" src="https://user-images.githubusercontent.com/38547944/204430865-ffc16771-90ca-43c7-903a-5451cb58c86c.png">
<img width="629" alt="image" src="https://user-images.githubusercontent.com/38547944/204430917-febf6ba1-eddc-4db0-b428-a00e7e651828.png">

4. pegasus+ranger

After completing the integration of ranger with pegasus, you can set permissions on the ranger web page according to your own needs
<img width="444" alt="image" src="https://user-images.githubusercontent.com/38547944/204432012-230db07c-47d0-4960-9c10-04340c19b2ff.png">
<img width="1382" alt="image" src="https://user-images.githubusercontent.com/38547944/204432186-344267c5-d966-4b21-99f5-cc6d4ade55db.png">
