### ISSUE TITLE
Apache Pegasus 2022 Meetup

### ISSUE THREAD

**Issue by GehaFearless** [apache/incubator-pegasus#1145]
## Apache Pegasus 2022 Meetup

*活动介绍*

> ***首次活动***

2021 年 9 月，Apache Pegasus 在小米科技园举办了首次 Meetup，此次活动获得了线上线下近千名参与者的极大认可，现场获得一致好评。

![image](https://user-images.githubusercontent.com/48315319/187151455-1d65455b-3858-420c-922e-d185c05c3aa4.png)

_Apache Pegasus 首次 Meetup 圆满落幕：https://mp.weixin.qq.com/s/Uc4dcTRSyrUbhDlEvfal1g_

> ***本次活动***

一年又如许，经过一年的洗礼，Apache Pegasus 又得到了成长，为促进社区与用户之间的交流，加强开发者之间的沟通，扩大社区的技术影响力，2022 我们再次出发。去年有两位神策的同学在 meetup 上进行了分享，此前不久神策获得了 Apache Pegasus 首个非小米产生的 committer，此次神策希望完成接棒奔跑，计划 11 月 5 日（周六）于北京海淀区量子芯座（地铁知春路站f口）举办新一届 Meetup。此次活动依旧会提供线上渠道进行参与，希望不能够到场的开源用户们也能够积极响应。

![image](https://user-images.githubusercontent.com/48315319/187154555-8cc8da38-5987-4909-8fa6-e8c4d223362e.png)

*会议内容*

> 新的变化

**Apache Pegasus 2.4.0 版本正在发版筹备中**

_2.4.0版本发版 issue：https://github.com/apache/incubator-pegasus/issues/1032_

**Apache Pegasus 迎来新的 committer 成员**

_committer 王聃：https://mp.weixin.qq.com/s/AbOPa5P4MBWRdqMLvlRDGQ_

> 投稿招募

Apache Pegasus 期待各位社区参与者的投稿以及分享，内容包括不限于：

- Pegasus 的设计原理、实现细节
- Pegasus 的功能特性、使用场景
- Pegasus 的部署与维护实践
- 如何在复杂业务中使用 Pegasus
- 如何使用 Pegasus 打造高可用数据仓库
- 如何参与 Apache Pegasus 的开源建设

Apache Pegasus 2022 Meetup 欢迎各位开源用户的参与！期待金风送爽的十月与您相遇。

**Comment by acelyc111** [comment]
Good news! Let's meet offline this October.

**Comment by GehaFearless** [comment]
非常抱歉的通知大家，由于疫情控制等多重原因，原计划于 10.22 进行的 2022 meetup，延期一周于 10.29 原场地进行，希望届时大家能够到场支持！

**Comment by acelyc111** [comment]
![image](https://user-images.githubusercontent.com/10775040/198078540-3af40c18-b66a-4925-8606-dd6f9611bf8d.png)

## 报名方式

扫描封面二维码↑↑↑

或戳 [这里](https://sdmarketing.wjx.cn/vm/PmUZLzu.aspx)

## 时间

2022.11.5（周六） 14:00~18:00

## 地点

北京市海淀区知春路27号量子芯座大厦

## 产品介绍

Apache Pegasus (incubating) 是一个可水平扩展、高性能、强一致的分布式Key-Value数据库，在日千亿级流量下可保证 P999 毫秒级的请求延迟，吞吐量高，数据持久化存储，对用户无感知的弹性扩缩容等运维操作。同时还有热备份、冷备份、Bulk Load、Partition Split、Backup Request 等丰富的功能。Apache Pegasus 的目标是服务数据规模大，对延迟敏感高，对数据有一致性和持久化存储需求的业务。

## 活动介绍

本次活动邀请了来自多家公司的Pegasus的研发运维团队、对Pegasus有深度使用的业务系统研发团队的核心成员，来分享他们是如何设计和实现Pegasus的核心功能、探究和扩展Pegasus的使用场景、结合业务系统特点来充分利用Pegasus，以及如何在复杂多样的私有化部署场景下，保障Pegasus能够稳定高效地部署和运行在1000多个客户环境中的。

### 参与本次Meetup，你能够

- 深入理解分布式KV存储系统的设计原理、实现细节和功能特性
- 获知Pegasus最新版本2.4.0的新特性、优化等改进
- 探讨如何结合Pegasus的特性，拓展他的使用场景，提升业务系统的能力
- 学习如何在私有云下支持 1000+ 客户的部署和运维
- 交流如何参与开源社区的共建
- 参与活动领取精美纪念品

**最后，我们还邀请了Pegasus的资深开发者来介绍RisingWave这个新兴的云原生流式数据库。**

## 活动议程

### 开场致辞

时间：14:00~14:15
张铎，Apache Pegasus mentor，Apache HBase PMC chair，神策数据首席架构师

---

### Apache Pegasus 2.4.0：构建更加高效、稳定与易用的KV系统

时间：14:15~14:50
分享人：贾硕，Apache Pegasus PPMC成员，前小米工程师，目前在字节跳动从事OLAP存储引擎研发

#### 内容简介

Apache Pegasus 2.4 是2022年发布的第一个稳定大版本。在该版本中，我们把更多社区生态工具引入到了Apache Pegasus项目中，同时提供了大量的新特性以增强系统的可靠性、易用性以及读写性能，例如新的日志引擎架构、全新的批量读取等。除此之外，针对Apache Pegasus的两个重点模块：Bulkload和Dupliction，我们在实践中做了大量的改进和重构，以更好的应对复杂的业务场景。本主题将介绍Apache Pegasus 2.4.0带来的全新变化。

---

### Apache Pegasus离在线融合建设与实践

时间：14:50~15:25
分享人：王伟，小米高级软件工程师，负责KV存储系统的研发工作

#### 内容简介

Apache Pegasus作为在线存储系统，与离线系统天然隔离。随着行业发展，HTAP概念出现，离在线的边界越来越模糊。Apache Pegasus支持离线能力的需求也越来越迫切，本主题将介绍Apache Pegasus针对离在线融合方面所做的工作。

---

### 小米通用推荐算法架构及Pegasus在用户画像中的应用

时间：15:25~16:00
分享人：梁伟，18年加入小米后一直从事推荐算法架构方面的工作，核心参与了高性能特征抽取工具及大规模并行打分服务的研发，目前负责小米应用商店、游戏中心、小米视频、电视视频等业务的推荐算法架构工作。

#### 内容简介

介绍小米应用商店、游戏中心、小米视频、电视视频及zili等业务中的推荐算法架构以及Pegasus在大规模用户画像中的应用。

---

### 茶歇时间

16:00~16:15

---

### 如何在复杂toB场景下对Pegasus进行持续改进

时间：16:15~16:50
分享人：王浩，神策数据分布式研发工程师，负责Pegasus存储的研发工作，Apache Pegasus社区的新生力量

#### 内容简介

分析Apache Pegasus在神策数据各个业务场景的数据特点，结合复杂多样的客户特征介绍神策是如何工程化管理上千家客户的，并根据神策客户需求讲述了Pegasus是如何接入数据迁移、鉴权、容器化等工作。

---

### Apache Pegasus在神策广告数据流中的应用

时间：16:50~17:25
分享人：史佼明，神策数据广告架构师，负责广告投放分析系统架构研发工作

#### 内容简介

介绍神策广告数据流架构以及 Apache Pegasus 在神策广告数据流中的应用。

---

### RisingWave：如何用云、流、数据库低成本开发实时应用

时间：17:25~18:00
分享人：吴涛，Apache Pegasus PPMC成员，前小米工程师，当前在RisingWave Labs担任产品经理

#### 内容简介

介绍RisingWave是如何通过流计算架构来开发实时应用，同时利用云原生的架构来降低部署成本，并结合数据库来提供极易上手的开发体验。

**Comment by acelyc111** [comment]
The meetup has been held successfully, thanks everybody!
![wecom-temp-450708-1c6c04295ea6efb5c4bff4703afb7eb8](https://user-images.githubusercontent.com/10775040/200256299-2b261fc2-eb87-44de-b430-dfc712385e05.png)
