### ISSUE TITLE
Refactor log macros

### ISSUE THREAD

**Issue by acelyc111** [apache/incubator-pegasus#1305]
There are two type of log macros in the code, one is using C string format specifiers, like `LOG_INFO`, the other is using `libfmt`, like `LOG_INFO_F`.

It's strange to keep the two macros in long term, I'm planning to refactor them and only leave `libfmt` style one.

**Comment by acelyc111** [comment]
Because there are so many code to be modified, I'll separet the whole work into smaller patches to make reviewers happy 😆 
- LOG_DEBUG
  - all
- LOG_INFO
  - replica module
  - meta module
  - others
- LOG_WARN
  - replica module
  - meta module
  - others
- LOG_WARN
  - replica module
  - others
- LOG_FATAL
  - all

**Comment by empiredan** [comment]
After all `LOG_*` macros have been replaced with `LOG_*_F`, would `LOG_*_F` be renamed as `LOG_*`? For example, `LOG_INFO_F` is renamed as `LOG_INFO` ?

**Comment by acelyc111** [comment]
Yes, I'm planning to still use `LOG_*_F` before all refactor work been finished, then remove `_F` postfix at last in one patch.

**Comment by acelyc111** [comment]
> After all `LOG_*` macros have been replaced with `LOG_*_F`, would `LOG_*_F` be renamed as `LOG_*`? For example, `LOG_INFO_F` is renamed as `LOG_INFO` ?

Yes, I'm planning to still use `LOG_*_F` before all refactor work been finished, then remove `_F` postfix at last in one patch.

**Comment by acelyc111** [comment]
> > After all `LOG_*` macros have been replaced with `LOG_*_F`, would `LOG_*_F` be renamed as `LOG_*`? For example, `LOG_INFO_F` is renamed as `LOG_INFO` ?
> 
> Yes, I'm planning to still use `LOG_*_F` before all refactor work been finished, then remove `_F` postfix at last in one patch.

In this way, all macros with or without `_F` postfix are both in the same semantics in the progress.

**Comment by empiredan** [comment]
> > > After all `LOG_*` macros have been replaced with `LOG_*_F`, would `LOG_*_F` be renamed as `LOG_*`? For example, `LOG_INFO_F` is renamed as `LOG_INFO` ?
> > 
> > 
> > Yes, I'm planning to still use `LOG_*_F` before all refactor work been finished, then remove `_F` postfix at last in one patch.
> 
> In this way, all macros with or without `_F` postfix are both in the same semantics in the progress.

I think it is important to keep all macros consistent without intermediate stages. Let's go ahead !

**Comment by Smityz** [comment]
Meticulous work! 
Can we add some checking of parameter count in the log function?
ref: https://github.com/fmtlib/fmt/issues/2593

**Comment by acelyc111** [comment]
> Meticulous work! Can we add some checking of parameter count in the log function? ref: [fmtlib/fmt#2593](https://github.com/fmtlib/fmt/issues/2593)

I assigned this work to you, you can implement it if you have time.

**Comment by acelyc111** [comment]
@GehaFearless Could you please to do the remain work?
LOG_WARN
- replica module
- meta module
- others

LOG_ERROR
- replica module
- others
