### ISSUE TITLE
Docker image build failed

### ISSUE THREAD

**Issue by acelyc111** [apache/incubator-pegasus#1347]
The docker image build failed when tis patch [1] merged, see [2].
@GehaFearless Could you please help to check and fix it?

1. https://github.com/apache/incubator-pegasus/commit/4476219048eea20155c54f58f9d7512f9f1af4e7
2. https://github.com/apache/incubator-pegasus/actions/runs/4115308630/jobs/7103848560

**Comment by GehaFearless** [comment]
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/48315319/218980206-1615fc53-47d5-4e23-9731-267db615d852.png">



This job has been a failure for a long time. Let me try it on local.
