### ISSUE TITLE
go mod tidy报错

### ISSUE THREAD

**Issue by lihenan1993** [apache/incubator-pegasus#1358]
`go mod tidy

        github.com/apache/incubator-pegasus/go-client/admin imports
        github.com/apache/incubator-pegasus/go-client/session imports
        github.com/apache/incubator-pegasus/go-client/idl/radmin: module github.com/apache/incubator-pegasus/go-client@latest found (v0.0.0-20230215061652-4c76112a5ded), but does not contain package github.com/apache/incubator-pegas
us/go-client/idl/radmin
`
测试文件 session_test.go 中引用的包 idle/rrdb , idle/replication 被删除了

**Comment by acelyc111** [comment]
@lihenan1993 您可以参考https://github.com/apache/incubator-pegasus/blob/master/.github/workflows/lint_and_test_go-client.yml#L38里面的步骤进行尝试。也就是像这里描述的一样 https://github.com/apache/incubator-pegasus/blob/master/go-client/Makefile#L18，需要先使用`thrift`来把 `*.thrift` 生成`*.go`到相应的目录下。
ps：这里移出之前目录文件的背景是，这些文件都是由thrift文件生成的，存在重复和过时的问题，所以编译时都现生成。

**Comment by lihenan1993** [comment]
您的出发点我可以理解，不过编译时现生成，会导致每个用到该库的程序，自动化部署都需要修改，对我们来说有些复杂。
感谢您的回答！
