### ISSUE TITLE
Add test bench type multi_set / multi_get

### ISSUE THREAD

**Issue by GehaFearless** [apache/incubator-pegasus#1372]
For our business, we found version 2.4 interface mutli_get & multi_get performance to be lower than 2.0.
So we need add bench type multi_get/multi_set test it.

**Comment by Smityz** [comment]
how about adding a benchmark test in the CI pipeline?

**Comment by acelyc111** [comment]
> how about adding a benchmark test in the CI pipeline?

+1, and we have to make sure the performance of the machine running CI is stable.
