### ISSUE TITLE
interface multi_get performance reduce

### ISSUE THREAD

**Issue by GehaFearless** [apache/incubator-pegasus#1382]
## Bug Report

We found version 2.4 interface multi_get performance to be lower than 2.0.

Through my efforts, discover thr pr on [del tls](https://github.com/XiaoMi/rdsn/commit/f9b9961e2c0b13faed157e7974e3783f5590ac53
) affects the outcome.

**Comment by GehaFearless** [comment]
Try to revert this pr back branch master.

**Comment by GehaFearless** [comment]
I use bench test interface multi_set & multi_get compare performance on same machine .

- Firstly, start onebox and fill data.

`./run.sh bench --type multisetrandom_pegasus --num 10000000 --app_name temp --timeout 20000`

- Then, stop onebox
- Start different verison onebox and read data.
`./run.sh bench --type multigetrandom_pegasus --num 5000000 --app_name temp --timeout 20000`

Compare before and after revert :

current branch master:    1758    1780    1778   ops/sec
after revert:                       2069   2036   2018   ops/sec

**Comment by GehaFearless** [comment]
I think we should revert 'tls' back.

**Comment by Smityz** [comment]
how about pasting more test details, like cpu/memory usage?
