### ISSUE TITLE
The client does not respond after the  replication  service is restarted

### ISSUE THREAD

**Issue by aubdiy** [apache/incubator-pegasus#1385]
## Bug Report

集群配置: 
1. 共 4 台服务器
2. 其中 3 台部署  meta , 
3. 每台服务器都部署 1 个 replic

问题场景:
1. 客户端使用 golang
2. 端从 kafka 中读取数据, 写入 pegasus
3. 当重启一台 replic  服务的时候

4 golang  客户端打印
time="2023-03-07T07:56:34Z" level=info msg="session [10.218.73.124:34801(replica)] is closed by the peer" func="session.(*nodeSession).loopForResponse" file="session.go:287"

replic重启成功(1 分钟左右)

但是 client 程序一致僵死, 没有写的数据写入
拜读源码,
发现一旦发生 rpc 网络关闭问题, 
session 就关闭退出了, 
当前协程不再处理任何事情

问题出现在 session.go 的 286 行, 
```
if rpc.IsNetworkClosed(err) { // EOF
    n.logger.Printf("session %s is closed by the peer", n)
   return nil
}
```

**Comment by PasunuriSrinidhi** [comment]
I want to work on this issue ,can you please assign this to me
