### ISSUE TITLE
support bulk load by creating and ingesting SST files

### ISSUE THREAD

**Issue by qinzuoyan** [apache/incubator-pegasus#139]
Though pegasus already provides `buld_load` usage scenario on table for faster write speed, it still uses `set` or `multiSet` inteface to insert data one by one. Definitely it is not fast enough to load very quite a lot of data (typically billions of rows) into Pegasus in a short time.

Maybe we can seek for a better way, considering:
- Rocksdb support [creating and ingesting SST files](https://github.com/facebook/rocksdb/wiki/Creating-and-Ingesting-SST-files)
- Pegasus support recovering table from external file system (such as HDFS) by loading RocksDB snapshots of each partition, through the [cold backup](https://github.com/XiaoMi/pegasus/wiki/%E5%86%B7%E5%A4%87%E4%BB%BD) feature. 

Then the idea is:
- construct RocksDB snapshots for each partition by offline computing (such as MapReduce), and store them on HDFS.
- recover table from HDFS by cold backup recovery.

**Comment by neverchanje** [comment]
@hycdong 把设计文档初稿记录在这里

**Comment by hycdong** [comment]
The basic idea is just as zuoyan's comment. We firstly create rocksdb SST files on remote storage such as HDFS, and ingest those files into pegasus. Rocksdb support [Creating-and-Ingesting-SST-files](https://github.com/facebook/rocksdb/wiki/Creating-and-Ingesting-SST-files). More details are below:

1. **Creating SST files on HDFS**
    -  Using RocksDBJava and Spark or MapReduce, write key-value pairs into SST files on HDFS
> Tips:
We plan to support converting files in specific format or HBase HFile into pegasus key structure, more details about this are already in discussion.

2. **Replica servers download SST files from HDFS**
    - Client send start bulk load request(including app and remote file storage informations) to meta server
    - Meta server send bulk load request to primary replica of each partition
    - Primary replica receive request from meta server and download SST files and notify secondaries download files and report its download progress
    - Secondary replica download SST files and report download progress through `group_check`
    - Primary replica report download progress to meta servers
    - Meta server will wait all partitions including primary and secondaries finish downloading
> Tips:
> 1. Primary and secondaries all download files from HDFS, so that we can avoid learn and data transfer through replicas which may affect normal read, write operations.
> 2. Server will restrict how many replica can download files at the same time
> 3. Download files task code has lower priority than normal write operations
> 
> In one word, we should guarantee downloading staging has minimal affect to normal user operations.

3. **Replica servers ingestion SST files**
    - Meta server send ingestion request to primary replica of each partition.
    - Primary replica will consider ingestion request as a special write request, execute 2pc staging
    - Write an empty request after primary commit to ensure secondaries commit ingestion request
> Tips:
> Rocksdb will **prevent write** operation during ingestion files, as a result, replica during ingestion staging will also reject all user operation. We should guarantee such time as short as possible.
