### ISSUE TITLE
Regularly build failed in recent

### ISSUE THREAD

**Issue by acelyc111** [apache/incubator-pegasus#1419]
In recent days, the regular build work flow failed, see https://github.com/apache/incubator-pegasus/actions/runs/4525900657

It is introduced by commit: e4fee118ca5a5ac48f57e862e6763666be22c1ce

**Comment by empiredan** [comment]
> There is another build failure on Ubuntu 16.04, see https://github.com/apache/incubator-pegasus/actions/runs/4540624560/jobs/8001768228
> 
> @empiredan

OK, I've created an issue to track this problem: https://github.com/apache/incubator-pegasus/issues/1424.

I'll propose a mail to discuss whether to no longer support compilation on ubuntu 1604/gcc 5.4.0.

**Comment by acelyc111** [comment]
So let's remove the supporting of Ubuntu 1604/gcc 5.4.0 ?

**Comment by acelyc111** [comment]
> So let's remove the supporting of Ubuntu 1604/gcc 5.4.0 ?

Done
