### ISSUE TITLE
fix install zk in branch v2.4

### ISSUE THREAD

**Issue by GehaFearless** [apache/incubator-pegasus#1513]
<img width="505" alt="image" src="https://github.com/apache/incubator-pegasus/assets/48315319/da273263-4d60-4767-a33e-7a94ab4e4891">

**Comment by acelyc111** [comment]
error details:
![image](https://github.com/apache/incubator-pegasus/assets/10775040/a6327ab7-3c12-4f18-8b34-b33c97a47bbe)
