### ISSUE TITLE
When primary meta server changes,this new function will throw an Index0utOfBoundsException.

### ISSUE THREAD

**Issue by asunyu1a** [apache/incubator-pegasus#1550]
## Bug Report

I use pegasus-2.4.

When primary meta server changes,this new function will throw an Index0utOfBoundsException.

If meta_a was killed,meta_b will be switched to primary meta immediately.Pegasus are available during this time,but this new function will throw an Index0utOfBoundsException and stop our program.

![企业微信截图_16877787986626](https://github.com/apache/incubator-pegasus/assets/46128522/fdffa2a7-9f15-4b25-831e-86b72dea104c)

![企业微信截图_16877788105516](https://github.com/apache/incubator-pegasus/assets/46128522/f61ac6df-65f1-457c-8f85-c3ef9b9c267c)

I use this method to connect pegasus.

![企业微信截图_16877788284157](https://github.com/apache/incubator-pegasus/assets/46128522/d6c6f4db-8f77-462e-8fce-86ab9698c706)

**Comment by acelyc111** [comment]
@asunyu1a It seems duplicate with https://github.com/apache/incubator-pegasus/issues/1410, it has been resolved in the lastest master branch.
