### ISSUE TITLE
Bug:(duplication) master cluster verify start decree error when restart a pause dup

### ISSUE THREAD

**Issue by ninsmiracle** [apache/incubator-pegasus#1595]
## Bug Report

When I restart a paused dup app on a recovered servers , the start decree of the duplication looking for will been loss,and those servers coredump agian.
It also has been occured online.

1. What did you do?
- Set meta level to lively firstly.
- Begin a duplication task firstly and wait for 5 minutes.
- Shut down two nodes of the master cluster, and then pause the duplication task immediately.
- Wait for one minutes,and restart the previously shut down nodes.
- Wait for ten minutes.(Give replica enough time to GC plog)
- Resume the duplication task 10 minutes later.
- Nodes which stopped just now core dump.

3. What did you see instead?
There are many coredump with the message "replica_duplicator::verify_start_decree" in master cluster.
```
#0  0x00007f968e6a01d7 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.17-157.el7_3.1.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.14.1-27.el7_3.x86_64 libcom_err-1.42.9-9.el7.x86_64 libgcc-4.8.5-28.el7_5.1.x86_64 libselinux-2.5-6.el7.x86_64 pcre-8.32-15.el7_2.1.x86_64 zlib-1.2.7-17.el7.x86_64
(gdb) #0  0x00007f968e6a01d7 in raise () from /lib64/libc.so.6
#1  0x00007f968e6a18c8 in abort () from /lib64/libc.so.6
#2  0x00007f969378763e in dsn_coredump ()
    at /home/jiashuo1/work/incubator-pegasus/src/rdsn/src/runtime/service_api_c.cpp:93
#3  0x00007f969364dc54 in dsn::replication::replica_duplicator::verify_start_decree (this=<optimized out>, start_decree=64525717)
    at /home/jiashuo1/work/incubator-pegasus/src/rdsn/src/replica/duplication/replica_duplicator.cpp:218   
#4  0x00007f969365ea05 in dsn::replication::load_from_private_log::run (
    this=0xa3016f040)
    at /home/jiashuo1/work/incubator-pegasus/src/rdsn/src/replica/duplication/load_from_private_log.cpp:71
#5  0x00007f96937c4631 in dsn::task::exec_internal (
    this=this@entry=0x90e7ce0f0)
    at /home/jiashuo1/work/incubator-pegasus/src/rdsn/src/runtime/task/task.cpp:176
#6  0x00007f96937d9ce2 in dsn::task_worker::loop (this=0x1c05600)
    at /home/jiashuo1/work/incubator-pegasus/src/rdsn/src/runtime/task/task_worker.cpp:224
#7  0x00007f96937d9e60 in dsn::task_worker::run_internal (this=0x1c05600)
    at /home/jiashuo1/work/incubator-pegasus/src/rdsn/src/runtime/task/task_worker.cpp:204
#8  0x00007f9692458a2f in execute_native_thread_routine ()
   from /home/work/app/pegasus/alsgsrv-monetization-master/replica/package/bin/libdsn_utils.so
#9  0x00007f9690263dc5 in start_thread () from /lib64/libpthread.so.0
#10 0x00007f968e76273d in clone () from /lib64/libc.so.6
(gdb) quit
```

4. What version of Pegasus are you using?
[pegasus2.4](https://github.com/apache/incubator-pegasus/tree/v2.4)

5.What happened?
FYI: the black word "duplicating" is a parameter of app_info. App_info file store in every replica's data dir.
![restart dup error](https://github.com/apache/incubator-pegasus/assets/110282526/6bc5bc42-d800-430a-98e0-bcea7d19085d)

**Comment by empiredan** [comment]
This issue has been fixed by https://github.com/apache/incubator-pegasus/pull/1608.
