### ISSUE TITLE
DISCUSS: remove the FDS supporting

### ISSUE THREAD

**Issue by acelyc111** [apache/incubator-pegasus#1644]
Hi, Pegasus developers and users,

As it known, the [FDS](https://docs.api.xiaomi.com/fds/introduction.html) is a Xiaomi internal storage system, the community users are not possible to use FDS as a [Backup](https://pegasus.apache.org/zh/administration/cold-backup) target, and since Pegasus [2.2.0](https://github.com/apache/incubator-pegasus/releases/tag/v2.2.0) (released in Jun, 2021), the Backup start to support using Apache HDFS as the target storage.

So I propose to terminate the supporting of FDS in the next version (maybe 2.6.0 or later). Of course, we will still fix critical bugs if there are in released versions.

Developers are also encouraged to contribute to support more public used storage systems, for example S3, OSS, COS and etc.

Looking forward to your reply!

**Comment by GiantKing** [comment]
I recommend keeping FDS, otherwise we have to maintain a new Pegasus branch internally. And keeping FDS, there is no impact on users to use other storages for backup.

**Comment by acelyc111** [comment]
@GiantKing Do you have a plan to use HDFS instead of FDS in your production environments? What's the blocker if not?

When developing new features or refactoring code, the community developers have to consider whether the FDS feature has been impacted or not, but they have no such a FDS testing enviroment to check it. It become a burden on the project in future developmemnt more or less.

**Comment by acelyc111** [comment]
If there isn't any more strong reasons to keep FDS related code in the project, I'm planing to remove these code.
Thanks!
