### ISSUE TITLE
Use thrift-maven-plugin to generate thrift sources instead of script

### ISSUE THREAD

**Issue by empiredan** [apache/incubator-pegasus#1664]
We could use [thrift-maven-plugin](https://mvnrepository.com/artifact/org.apache.thrift/thrift-maven-plugin) to generate thrift sources instead of scripts, just like what parquet has done:

- https://issues.apache.org/jira/browse/PARQUET-1506
- https://github.com/apache/parquet-java/pull/600
- https://github.com/apache/parquet-java/blob/master/parquet-format-structures/pom.xml

**Comment by shalk** [comment]
@empiredan  parquet link is broken

**Comment by empiredan** [comment]
> @empiredan parquet link is broken

Sorry for the late reply. Have updated the description.
