### ISSUE TITLE
After upgrading from 2.4.0 to 2.5.0, some replicas frequently encounter 'client read accounted for an unhandled error'

### ISSUE THREAD

**Issue by chendongjiu** [apache/incubator-pegasus#1832]
## Bug Report

![Vc47SSlm8O](https://github.com/apache/incubator-pegasus/assets/12393042/f71bdb32-96ad-4381-a38b-a4b861cea952)

Besides having a large number of error logs like this, the replica can work properly

**Comment by acelyc111** [comment]
@chendongjiu Thanks for the reply!

This is resolved by https://github.com/apache/incubator-pegasus/commit/82d981f51cf5e7b22971f9ac3f26f02a063600fe on master branch and cherry-picked to branch v2.5 as https://github.com/apache/incubator-pegasus/commit/d59b7579df83784a53f006cb3d5cd51c64dc0ff4
