### ISSUE TITLE
Meta_server unable to connect kerberos zookeeper where KDC configuration "rdns = false"

### ISSUE THREAD

**Issue by GehaFearless** [apache/incubator-pegasus#1863]
## Feature Request

/etc/krb5.conf
![image](https://github.com/apache/incubator-pegasus/assets/48315319/cef98f5c-7691-475e-87ad-9d767e92de06)

I need to deploy Pegasus on machine configured with KDC as above.
At the same time, ZooKeeper enables SASL restrictions on some znodes.

I got error as follow.

zookeeper client log
`2024-01-19 21:37:26,792:13938(0x7fe9d9852700):ZOO_INFO@check_events@2988: initiated connection to server x.x.x.x:2181
2024-01-19 21:37:26,795:13938(0x7fe9d9852700):ZOO_ERROR@zoo_sasl_client_start@287: Starting SASL negotiation: generic failure SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Server zookeeper/x.x.x.x@REALMS.COM not found in Kerberos database)
2024-01-19 21:37:26,795:13938(0x7fe9d9852700):ZOO_ERROR@_zsasl_fail@148: SASL authentication failed. rc=-1`

kdc log
`Jan 19 21:37:26 cdh01.newcluster.com krb5kdc[18354](info): TGS_REQ (8 etypes {18 17 20 19 16 23 25 26}) x.x.x.x: LOOKING_UP_SERVER: authtime 0,  pegasus/FQDN1@REALMS.COM  for zookeeper/x.x.x.x@REALMS.COM, Server not found in Kerberos database
`

FQDN `FQDN1`correspond to IP `x.x.x.x`

zookeeper service principal are `zookeeper/x.x.x.x@REALMS.COM`

**Comment by empiredan** [comment]
Have we tried to set `host` in `zoo_sasl_params_t` with `NULL` ? 

```
typedef struct zoo_sasl_params {
  const char *service;          /*!< The service name, usually "zookeeper" */
  const char *host;             /*!< The server name, e.g. "zk-sasl-md5" */
  const char *mechlist;         /*!< Mechanisms to try, e.g. "DIGEST-MD5" */
  const sasl_callback_t *callbacks;  /*!< List of callbacks */
} zoo_sasl_params_t;

ZOOAPI zhandle_t *zookeeper_init_sasl(const char *host, watcher_fn fn,
  int recv_timeout, const clientid_t *clientid, void *context, int flags,
  log_callback_fn log_callback, zoo_sasl_params_t *sasl_params);
```

I found that `host` would be set automatically if it was `NULL`:

```c
int zoo_sasl_connect(zhandle_t *zh)
{
......
    rc = _zsasl_getipport(zh, (const struct sockaddr *)&local_ip, salen,
        iplocalport, NULL);
    if (rc < 0) {
        return _zsasl_fail(zh, rc);
    }

    salen = sizeof(remote_ip);
    if (getpeername(zh->fd->sock, (struct sockaddr *)&remote_ip, &salen) < 0) {
        LOG_ERROR(LOGCALLBACK(zh), "getpeername");
        return _zsasl_fail(zh, ZSYSTEMERROR);
    }

    rc = _zsasl_getipport(zh, (const struct sockaddr *)&remote_ip, salen,
        ipremoteport, host);
    if (rc < 0) {
        return _zsasl_fail(zh, rc);
    }
......
    /* client new connection */
    sr = sasl_client_new(
        sc->params.service,
        sc->params.host ? sc->params.host : host,
        iplocalport,
        ipremoteport,
        sc->params.callbacks,
        /*secflags*/0,
        &sc->conn);

    if (sr != SASL_OK) {
        LOG_ERROR(LOGCALLBACK(zh),
            "allocating SASL connection state: %s",
            sasl_errstring(sr, NULL, NULL));
        return _zsasl_fail(zh, ZSYSTEMERROR);
    }

    return ZOK;
}
```
