### ISSUE TITLE
pegasus uses a non OSS friendly version of org.json:json jar

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pegasus#1919]
https://github.com/apache/incubator-pegasus/blob/af256941f4062c77377d05d379ebd7f9b4a327ee/java-client/pom.xml#L68

See https://www.apache.org/legal/resolved.html (JSON license section)

Could you upgrade to a newer version? And these versions have security fixes too.

Since late 2022, this jar is now properly in the public domain.

**Comment by empiredan** [comment]
> https://github.com/apache/incubator-pegasus/blob/af256941f4062c77377d05d379ebd7f9b4a327ee/java-client/pom.xml#L68
> 
> See https://www.apache.org/legal/resolved.html (JSON license section)
> 
> Could you upgrade to a newer version? And these versions have security fixes too.
> 
> Since late 2022, this jar is now properly in the public domain.

Thanks @pjfanning ! Upgraded by https://github.com/apache/incubator-pegasus/pull/1781.
