### ISSUE TITLE
Bug(go client):Go client fails to compile.

### ISSUE THREAD

**Issue by lengyuexuexuan** [apache/incubator-pegasus#1947]
## Bug Report

1. What did you do?
the go client  failed to compile.
![1](https://github.com/apache/incubator-pegasus/assets/46274877/69c2ccdc-958e-479d-bafb-e0c34ac26263)

2. What did you expect to see?
the go client can compile.

3. What version of Pegasus are you using?
the lastest version.

**Comment by acelyc111** [comment]
Thanks! Fixed in https://github.com/apache/incubator-pegasus/pull/1946.

Tips: It would be better to paste text rather than picture, the text content can be easily searched.
