### ISSUE TITLE
Support configurating different compression algorithms for different levels

### ISSUE THREAD

**Issue by qinzuoyan** [apache/incubator-pegasus#236]
最好是支持节点级和表级的配置：
* 节点级：类似现在的 rocksdb_compression_type = snappy，最好是在这上面扩展并保持兼容，譬如：
  * rocksdb_compression_type = snappy，兼容老的(只对level>=2进行设置)
  * rocksdb_compression_type = per_level:none,lz4,zstd  (数组下标从0开始；如果设置的数组长度大于num_levels，则将多余的忽略；如果设置的数组长度小于num_levels，则后面的都用最后一个type补齐)
* 表级：类似replica.write_throttling，用户可以通过env设置rocksdb.compression_type，该值会覆盖节点级配置rocksdb_compression_type 。如果env的value出现格式错误或者不支持的压缩方式，则使用节点级配置rocksdb_compression_type 。

**Comment by acelyc111** [comment]
@acelyc111
