### ISSUE TITLE
improve assign strategy to balance multiple disks usage

### ISSUE THREAD

**Issue by qinzuoyan** [apache/incubator-pegasus#261]

**Comment by mentoswang** [comment]
replica_stub::open_replica -> replica_stub::get_replica_dir -> fs_manager::allocate_dir:

    for (auto &n : _dir_nodes) {
        dassert(!n->has(pid),
                "gpid(%d.%d) already in dir_node(%s)",
                pid.get_app_id(),
                pid.get_partition_index(),
                n->tag.c_str());
        unsigned app_replicas = n->replicas_count(pid.get_app_id());
        unsigned total_replicas = n->replicas_count();
        if (selected == nullptr || least_app_replicas_count > app_replicas) {
            least_app_replicas_count = app_replicas;
            least_total_replicas_count = total_replicas;
            selected = n.get();
        } else if (least_app_replicas_count == app_replicas &&
                   least_total_replicas_count > total_replicas) {
            least_total_replicas_count = total_replicas;
            selected = n.get();
        }
    }

**Comment by Shuo-Jia** [comment]
## 总体原则：
* “node rebalancer”和“disk rebalancer”是解耦的，同时倾向于手动触发“ssd rebalance”，类似于HDFS DiskRebalancer 命令行触发的方式。
* 整个功能分为两部分：
（1）均衡评估：以表为单位，评估每个表的primary、secondary在磁盘上是否均衡，给出磁盘分片的分布情况、容量使用情况，并计算当前的均衡度量值。同时在节点级别以类似均方差的形式计算当前节点所有磁盘、所有表的总的均衡度。
（2）均衡策略：以表为最小决策单位，以分片为最小迁移单位，遍历每个表分别实现单表的primary、secondary均衡，进而实现磁盘的全局均衡。
* 均衡评估和均衡策略的执行有replicaServer来执行，如果需要使用shell脚本查看所有节点的均衡状态，则需要把所有节点的均衡评估的结果、均衡策略执行的状态交由metaServer来同时维护。但是均衡策略的执行依然由replicaServer来创建和执行（这点区别node rebalancer中metaServer维护均衡策略的生成）。
## 总体框图
![image2020-2-13_18-8-17](https://user-images.githubusercontent.com/23136769/74514838-5c1f0d80-4f48-11ea-9d75-93cac5beea46.png)

**Comment by Shuo-Jia** [comment]
## 总体原则：
* “node rebalancer”和“disk rebalancer”是解耦的，同时倾向于手动触发“ssd rebalance”，类似于HDFS DiskRebalancer 命令行触发的方式。
* 整个功能分为两大部分：
（1）均衡评估：以表为单位，评估每个表的primary、secondary在磁盘上是否均衡，给出磁盘分片的分布情况、容量使用情况，并计算当前的均衡度量值。同时在节点级别以类似均方差的形式计算当前节点所有磁盘、所有表的总的均衡度。
（2）均衡策略：以表为最小决策单位，以分片为最小迁移单位，遍历每个表分别实现单表的primary、secondary均衡，进而实现磁盘的全局均衡。
* 均衡评估和均衡策略的执行有replicaServer来执行，如果需要使用shell脚本查看所有节点的均衡状态，则需要把所有节点的均衡评估的结果、均衡策略执行的状态交由metaServer来同时维护。但是均衡策略的执行依然由replicaServer来创建和执行（这点区别node rebalancer中metaServer维护均衡策略的生成）。
## 总体框图
![image2020-2-13_18-8-17](https://user-images.githubusercontent.com/23136769/74514838-5c1f0d80-4f48-11ea-9d75-93cac5beea46.png)
* 黑色部分为Pegasus已有的类，红色为新增的类。
* command模块负责balance命令的下发和执行。主要的逻辑由replica_server模块实现（以replica_stub作为入口），但相关请求由meta_server模块（以server_state作为入口）统一下发，相关数据、状态由meta_server模块维护，并与replica_server模块同步（meta_server模块是虚线，代表该模块可讨论是否必要）
* 所有的请求包括：
（1）query_disk_info: 查看当前的个节点的磁盘均衡状态，包括磁盘利用率、分片分布等。该模块需要借助fs_manager实现。
（2）create_disk_balance_policy: 创建某个节点的均衡策略的具体步骤。该模块依赖disk_balancer_policy实现，而disk_balancer_policy则需要借助fs_manager维护的disk信息进行计算
（3）excute_disk_balance(): 根据创建好的步骤执行数据迁移拷贝任务，迁移拷贝的实际执行依赖disk_balancer_service,并最终借助nfs_node、replica_chkpt来执行。实际迁移策略的执行，需要按照replica_learn模块的步骤来进行，即：先复制→后回放，但是replica_learn的方法应该是不能复用了，而改为借鉴节点迁移逻辑，重写本地迁移逻辑。另外，nfs_node类的节点间迁移数据都是由RPC进行通信，但是实际本地迁移已经不必要了。 
（4）query_disk_balance_stats(): 查看当前的执行状态。
（5）cancel_disk_balance():取消现在的磁盘均衡策略的执行。
## 核心模块设计
### 分片均衡状态设计
![image2020-2-10_17-23-20](https://user-images.githubusercontent.com/23136769/74516340-2f202a00-4f4b-11ea-8a9b-bb96c821989e.png)
* 已有的meta_server分片均衡状态计算的逻辑：bool greedy_load_balancer::calc_disk_load，整个逻辑如上图。可以看到，server_state通过rpc获取了app_info原始信息并生成app_mapper信息给greedy_load_balancer用，该模块在使用的时候通过meta_data的get_node_state和get_config_context提取的信息最终生成了disk_load——meta_server对从replica_stub获取的原始信息做了大量的重新封装，而后才计算出disk_load。
* 由于meta_server自有自己的一些“config信息”封装规则，所以与replica复用一些逻辑是很难的，一个推荐的做法的是：replica_stub把disk_load信息计算完成后可以直接同步给meta_server使用，而不用使用目前这么复杂的逻辑。
* 在当前的设计中，倾向于重新为replica_stub设计自己的disk_load信息，设计如下：
![image2020-2-10_20-53-33 (1)](https://user-images.githubusercontent.com/23136769/74518089-385ec600-4f4e-11ea-9a62-041fd932aff2.png)
（1）fs_manager管理所有的disk信息(_sorted_dir_nodes/_dir_nodes)，并根据disk的信息计算均衡度——compute_disk_density()
（2）dir_node管理当前disk下的容量和分片信息（holding_replicas/holding_primary_replicas），并根据均衡度重写dir_node的排序信息
（3）节点利用率total_used_ratio，磁盘利用率disk_used_ratio，则均衡度为disk_density = disk_used_ratio-total_used_ratio
（4）定义磁盘容量disk_capacity，则可迁移最大数据量max_move = abs(disk_capacity*total_used_ratio - disk_used)
（5）节点均衡度node_density = sum(abs(disk_density))
### 均衡策略生成设计
![image2020-2-14_10-22-29 (1)](https://user-images.githubusercontent.com/23136769/74518284-82e04280-4f4e-11ea-9bce-f8eff8e115d8.png)
* 均衡策略生成由disk_balancer_policy类来完成，其计算原则为：以表为单位，把所有分区的该表分片数据的均衡状态进行排序，每次选举最大、最小容量的两个分区进行迁移，迁移完成后更新现在的的分区均衡状态，循环执行，直到认为当前已经均衡。计算方式为：
最大可迁移量 = 绝对值(磁盘容量*节点磁盘利用率- 该磁盘使用量)，需要注意的是：最大可迁移量最终需要转换为“最大可迁移分片”：最大可迁移分片=最大可迁移量/单分片容量
* 如“分片均衡状态设计”所述，fs_manager存储了所有磁盘的容量均衡信息和分片均衡信息，disk_balancer_policy需要借助这些信息进行排序、计算。
* disk_balancer_actions存储了一次均衡操作的所有步骤，每个迁移（move_action）主要包含迁移源（source），迁移目的地（destination），迁移量（move_bytes/move_replica）
* 需要注意的是，每次生生成一个步骤，需要更新当前的磁盘均衡状态（compute_disk_density）
### 数据迁移执行设计
### 关于node rebalancer：
![image2020-2-14_11-23-40 (1)](https://user-images.githubusercontent.com/23136769/74518379-b28f4a80-4f4e-11ea-93e6-c4f004140441.png)
* 图示是现有的node rebalance时数据的迁移步骤，由于node rebalancer涉及不同的节点通信，所以定义了learner和leanee两个角色，并且通过RPC进行通信
* learner通过init_learn方法首先要更新当前未提交的request，并且通过“catch_up_with_logs”循环执行日志“同步操作”，随后发起RPC通信，learnee收到请求后比对当前的decree，并且分别处理mutation数据、checkpoint数据、plog数据，并返回给learner。核心数据存储在learn_state中。learner通过on_learn_reply处理响应，通过nfs→copy_remote_files拷贝远端数据，最终通过on_copy_remote_state_completed分别处理checkpoint和plog，同样该逻辑是是循环执行的，最终依然要回到init再次发起同步请求，保证数据完备性。
* 疑问：mutation数据的处理没有明白。
### 关于disk rebalancer：
* disk rebalancer少了网络通信的步骤，所以实际设计仅需要“learner”中的“init_learn”逻辑即可，即不断的catch_up_with_private_logs保证数据的完整和同步即可。
* 迁移步骤：learn过程数据迁移包含三个部分——迁移磁盘数据、迁移mutation数据、迁移plog数据。对于disk rebalancer来说，不同的磁盘共用“mutation”数据，所以实际的步骤如下：
（1）为待迁移的数据创建“checkpoint”，目标路径为“目标迁移路径”
（2）使用plog回放新增的数据，并写入到新的路径下
（3）变更mutation的目标的路径为新的路径（需要调研具体实现）
* 数据完整：
（1）在迁移的过程中，包括回放plog的过程中，新的请求数据会时刻写入到旧的replica路径下，所以为了保证数据完整性，需要参考learn的catch_up_with_private_logs进行回放日志。
（2）checkpoint的数据和原始路径的文件会有差异（log文件等），需要考虑是否需要二次拷贝。
* 状态变更：learn在数据的迁移过程中，会使learner的replica置为“PS_POTENTIAL_SECONDARY”，disk rebalancer需要设计类似的状态机变化，以保证状态的切换对数据的访问的合理性
（1）disk rebalancer的数据迁移可能会导致同一个node下产生两个相同的replica，所以需要注意同名replica对replica_server造成的影响
（2）新增的replica的状态可以设置成invalid状态，直至确定数据已经完整，随后改为secondary状态，并把旧的replica置为invalid
## 开发计划
### 总体原则：
* command和meta_server（包括meta_server与command、replica_server通信与同步逻辑）暂时不予关注，专注实际disk rebalancer模块的设计
### 具体步骤：
* 磁盘的均衡状态信息功能开发
* 磁盘均衡策略开发
* 磁盘均衡策略模拟测试开发
* 磁盘均衡数据迁移功能开发
* meta_server和replica_server数据通信与同步开发
* command模块开发
### 难点：
* 磁盘数据迁移的一致性和完整性
* 均衡策略的有效性
## 其他问题
* **为什么以表为单位进行均衡？** 对于任意一个表，我们认为每个replica的大小都是一样的。所以当每个表的primary、secondary在ssd的分布均衡时，则理想情况下ssd的primary、secondary是均衡的，ssd全局磁盘利用率是均衡的。这种“磁盘均衡”是较为“彻底的均衡”，既满足“容量的均衡”，又满足“负载的均衡”——其本质上是和“node rebalancer”一个原理和效果。
* **以表为单位进行均衡，是否对SSD 整体均衡有误差？**  当primary和secondary的数量无法整除SSD数量时，将会带来累积误差，而且这种误差如果不在后续迭代每个表进行均衡的的时候处理妥善，将会随着表的数量的增加而越来越大，因此大致的设计思路是：
（1）初始状态，当无法整除的时候，将随机选择一些磁盘进行分配
（2）当继续其余表的均衡的时候，将优先选择磁盘分片数较少、且磁盘容量利用率小的磁盘进行分配
* **数据迁移的开销怎么样？** 基于每个表进行迁移以达到SSD全局的磁盘均衡策略，将会出现很多“多余的”replica迁移(实际是不同表的replica交换)，例如2个SSD，2个表,以primary为例：5个tableA_pri + 1个tableB_pri | 1个tableA_pri + 5个tableB_pri，如果从全局来看，磁盘容量均衡、请求负载均衡，则就达到了我们的“均衡目的”，但是该策略中表是最小的决策单位，所以我们依然需要更换不同的表的replica，这将增大均衡策略中迁移数据的开销。但是如果我们严格需要每个表在SSD的分布都是均衡的，这种开销是不可避免的。
* **均衡策略的有效性怎么样？** 目前的disk均很策略借鉴HDFS DiskBalancer的思想，并基于Pegasus的表级特性、分片特性进行实现。至于效果需要后续实现简单的Simulator进行测试。
