### ISSUE TITLE
Toolset - migrate HBase files to Pegasus

### ISSUE THREAD

**Issue by hycdong** [apache/incubator-pegasus#342]
Many users used to write their data to HBase, for some reasons, they would like to use Pegasus now. Besides, they also would like to migrate their large amount of data from HBase to Pegasus. 
Unfortunately, bulk load function is still in development, we need to develop a simpler solution to solve creating table with large data.

Usage situation:
- migrate data when creating table

Basic idea:
1. Use Spark or MR to write HFiles data to RocksDB run over HDFS
2. Get checkpoint of RocksDB and construct a valid cold backup
3. Restore table from cold backup

**Comment by windshg** [comment]
In our case, we actually have following scenes:
