### ISSUE TITLE
Use original rocksDB

### ISSUE THREAD

**Issue by acelyc111** [apache/incubator-pegasus#468]
The rocksDB library Pegasus now uses has some special modifications, we'd better remove these changes and use original rocksDB, and then we can upgrade the dependent rocksDB library freely.

## Modifications
Pegasus-rocksdb has the following modifications:

1.  set/get LastFlushedDecree
2. get PegasusDataVersion
3. get LastManualCompactFinishTime and update internally
4. Add a new CreateCheckpointQuick, this function 

## How to remove these modifications?
For 1, 2 and 3, these values are store in manifest now, we can store these meta infomation in another column family instead.
For 4, CreateCheckpointQuick has the same logic with CreateCheckpoint, and extractly return the last decree, we can CreateCheckpoint and then read the last decree from the check point instead.

## Steps
1.
- Upgrade rocksdb to the latest stable version. We will use some new featue like `atomic_flush`, `read skip memtable` in the following steps.

2. 
- Store `last_decree`, `data_version`, `last_manual_compact_finish_time` both in manifest and another column family.
- Read these values from manifest.

3. 
- Store and reads these values from the other column family.

**Comment by acelyc111** [comment]
We need to flush data CF and meta CF atomically, it's support since [rocksdb 5.18.3](https://github.com/facebook/rocksdb/releases/tag/v5.18.3), doc https://github.com/facebook/rocksdb/wiki/Atomic-flush

**Comment by l2dy** [comment]
FWIW, would this make Pegasus compatible with ByteDance's [terarkdb](https://github.com/bytedance/terarkdb)?

**Comment by acelyc111** [comment]
> FWIW, would this make Pegasus compatible with ByteDance's [terarkdb](https://github.com/bytedance/terarkdb)?

In theory, it's compatible if terarkdb's APIs are compatible with rocksdb. terarkdb seems interesting to adapt to Pegasus.
And in fact, we're planing to use https://github.com/tikv/rocksdb/tree/titan-5.15 to reduce write amplification in the future.
