### ISSUE TITLE
Limit long-time running Scan/MultiGet operators

### ISSUE THREAD

**Issue by qinzuoyan** [apache/incubator-pegasus#486]
## Feature Request

**Is your feature request related to a problem? Please describe:**
Sometimes Scan/MultiGet operators may run for long time because of too many expired or filtered data, which may cause CPU/IO busy and make server unavailable. We should limit these long-time running Scan/MultiGet operators, for example:
* limit max rows or bytes to scan (including expired and filtered data) in one request
* limit max running time to process in one request

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by hycdong** [comment]
Pegasus server:
- muliget
  1. add max_iterator_count check, including expire_count and filter_count
  2. add max_iterator_size check, client may set max_kv_size as -1 means no-limit, server should set a max threshold
  3. add max_execute_time check to avoid long time scan
- scan
   1. add max_iterator_count_for_one_scanner check, including expire_count and filter_count
   2. add max_execute_time check
- sortkey_count
   1. add max_execute_time check
Options above are cluster level, and can also set by app_envs for each table. (consider it)
If iterator exceed count or size or time limit, server should return rocksdb Incomplete error (just like multiget)

Pegasus java client:
- multiGet (no need to update)
- sortKeyCount if got Incomplete error, return -1, not throw exception
- scan: not throw exception if got Incomplete error, and stop asyncNext if failed several times
- delRange: stop if scan got Incomplete error

Pegasus C++ client:
- interface update same as java client
- copy_data
- clear_data
- count_data
