### ISSUE TITLE
GCC 9.2.0 编译错误

### ISSUE THREAD

**Issue by darionyaphet** [apache/incubator-pegasus#595]
## Bug Report

GCC 9.2.0 编译错误 按照下列命令运行：

```
git clone https://github.com/xiaomi/pegasus.git --recursive
cd pegasus

git checkout -b v1.11.4 v1.11.4
git submodule update

./run.sh build -c
```

出现如下错误

```
src/zookeeper.c: In function 'format_endpoint_info':
src/zookeeper.c:3469:21: error: '%d' directive writing between 1 and 5 bytes into a region of size between 0 and 127 [-Werror=format-overflow=]
 3469 |     sprintf(buf,"%s:%d",addrstr,ntohs(port));
```

**Comment by vagetablechicken** [comment]
We shouldn't change zookeeper source（thirdparty）. So you could disable `-Werror` in `Makefile.am:AM_CFLAGS = -Wall -Werror`, then rebuild thirdparty.

**Comment by neverchanje** [comment]
BTW, 1.11.4 is an old version. We are striving to make the latest version robust and buildable. Please use the version as latest as possible.

**Comment by Smityz** [comment]
If you are using Ubuntu 20.04, you can use gcc-7/g++-7
