### ISSUE TITLE
The readme page still references lots of resources of Xiaomi

### ISSUE THREAD

**Issue by Apache9** [apache/incubator-pegasus#606]
At least in the Contact section, we should change the url of issues to the new place, and also add our mailing list to it?

And for the submodules and client libs, have we already moved them to apache or they are still under the control of Xiaomi? For former we should change the url, for latter then we need to start the process of also donating these projects?

**Comment by neverchanje** [comment]
Thank you for your reminding. I've committed a PR for this https://github.com/apache/incubator-pegasus/pull/609/files.

Submodules and client libs were donated to ASF as well, as we included them in the SGA. But they are not transferred yet. That's what we certainly need to work out.

**Comment by vongosling** [comment]
It is better to use the apache domain instead of the previous Pegasus Website, while it is now directed to the site under the apache domain.
