### ISSUE TITLE
v2.1 build error 

### ISSUE THREAD

**Issue by totalo** [apache/incubator-pegasus#622]
common.copy lib/libboost_regex.a
...updated 14820 targets...
[ 77%] Performing install step for 'boost'
[ 77%] Completed 'boost'
[ 77%] Built target boost
make: *** [Makefile:84：all] 错误 2

**Comment by Smityz** [comment]
> common.copy lib/libboost_regex.a
> ...updated 14820 targets...
> [ 77%] Performing install step for 'boost'
> [ 77%] Completed 'boost'
> [ 77%] Built target boost
> make: *** [Makefile:84：all] 错误 2

what is your boost gcc cmake's version

**Comment by totalo** [comment]
> > common.copy lib/libboost_regex.a
> > ...updated 14820 targets...
> > [ 77%] Performing install step for 'boost'
> > [ 77%] Completed 'boost'
> > [ 77%] Built target boost
> > make: *** [Makefile:84：all] 错误 2
> 
> what is your boost gcc cmake's version

gcc --version
gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by Smityz** [comment]
> > > common.copy lib/libboost_regex.a
> > > ...updated 14820 targets...
> > > [ 77%] Performing install step for 'boost'
> > > [ 77%] Completed 'boost'
> > > [ 77%] Built target boost
> > > make: *** [Makefile:84：all] 错误 2
> > 
> > what is your boost gcc cmake's version
> 
> gcc --version
> gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0
> Copyright (C) 2019 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> 
> 

gcc version is too high, recommand use 5.4.0.If you are using ubuntu20, It is also compatible with g++-7

**Comment by totalo** [comment]
ok, THKS

**Comment by 765308949** [comment]
common.copy lib/libboost_regex.a
...updated 14820 targets...
[ 55%] Performing install step for 'boost'
[ 55%] Completed 'boost'
[ 55%] Built target boost
make: *** [all] Error 2
ERROR: build rdsn failed

gcc版本已经修改了，还是不行，请帮忙看下，谢谢。
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-unknown-linux-gnu/5.4.0/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: ../configure --enable-checking=release --enable-languages=c,c++ --disable-multilib
Thread model: posix
gcc version 5.4.0 (GCC)

**Comment by neverchanje** [comment]
请用下面命令，用1线程编译试试：

```sh
cd rdsn
./run.sh build -j 1
```

编译可以借鉴 http://pegasus.apache.org/docs/build/compile-by-docker/，推荐用docker编译

**Comment by 765308949** [comment]
您好单线程编译 ./run.sh -j 1是这个命令吗？

**Comment by 765308949** [comment]
CMake Error at /usr/local/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
  Could NOT find zstd (missing: zstd_LIBRARIES zstd_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:582 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/Findzstd.cmake:17 (find_package_handle_standard_args)
  CMakeLists.txt:131 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/pagesus/apache-pegasus-2.1.0-incubating-src/rdsn/thirdparty/build/Build/rocksdb/CMakeFiles/CMakeOutput.log".
make[2]: *** [Stamp/rocksdb/rocksdb-configure] Error 1
make[1]: *** [CMakeFiles/rocksdb.dir/all] Error 2
make: *** [all] Error 2

请问这种情况应该怎么处理呢？

**Comment by neverchanje** [comment]
Could NOT find zstd (missing: zstd_LIBRARIES zstd_INCLUDE_DIRS)

正如这条错误显示的，你没有安装zstd，你应该是没有正确按照文档安装依赖。http://pegasus.apache.org/docs/build/compile-by-docker/

**Comment by 765308949** [comment]
好的 我这边重新安装一次  谢谢
