### ISSUE TITLE
the document maybe have error

### ISSUE THREAD

**Issue by shenxingwuying** [apache/incubator-pegasus#636]
## General Question

1、 The pegasus doc maybe error.
http://pegasus.apache.org/overview/benchmark/
The latency is ms? That's not reasonable. I guess the author of doc make a mistake.

![image](https://user-images.githubusercontent.com/6360122/98196833-23a0e300-1f60-11eb-841a-7b8db6dca0b0.png)

2、Some url links are not found, eg:
![image](https://user-images.githubusercontent.com/6360122/98196924-6b276f00-1f60-11eb-83ce-31ef04ddf8c8.png)

At http://pegasus.apache.org/overview/， 
![image](https://user-images.githubusercontent.com/6360122/98197001-99a54a00-1f60-11eb-9964-6e73490f1d55.png)   Page Not Found

**Comment by neverchanje** [comment]
Thank you for finding the mistakes! I've now fixed them already, except for the incorrect benchmark results.
I'm not the author of the benchmark. @Shuo-Jia will handle this.

**Comment by Shuo-Jia** [comment]
> Thank you for finding the mistakes! I've now fixed them already, except for the incorrect benchmark results.
> I'm not the author of the benchmark. @Shuo-Jia will handle this.

Yes, It's my mistake, I have updated it, see https://pegasus.apache.org/overview/benchmark/. thanks again! @shenxingwuying

**Comment by shenxingwuying** [comment]
Good
