### ISSUE TITLE
pegasus文档中不直接支持list数据格式

### ISSUE THREAD

**Issue by 765308949** [apache/incubator-pegasus#668]
您好，看了官方文档发现pegasus不直接支持list数据格式，但是可以参考pika的实现形式，我理解是需要自己在代码里面根据pika的实现方案写一个list的存储方式吗？还是说有现成的api可以调用。

**Comment by neverchanje** [comment]
没有现成的api。简单的实现方法是把 key 放到 hashkey，把 list index 作为 sortkey。但这种实现需要注意把 key 打散，避免单个 list 过大，引起热点问题。

**Comment by 765308949** [comment]
好的 谢谢了
