### ISSUE TITLE
pegasus-kv/pegasus-spark java项目构建失败

### ISSUE THREAD

**Issue by shamomanba** [apache/incubator-pegasus#692]
构建的失败信息如下：
![image](https://user-images.githubusercontent.com/19187765/107326033-bc0dad00-6ae5-11eb-9087-0f91f063e087.png)
请问一哈，这几个jar包是在哪个镜像仓库里呢？

**Comment by Shuo-Jia** [comment]
see https://github.com/pegasus-kv/pegasus-spark/issues/53
