### ISSUE TITLE
Feature: table level compaction perf-counter

### ISSUE THREAD

**Issue by hycdong** [apache/incubator-pegasus#744]
## Feature Request
Rocksdb compaction is disk-consuming, cpu consuming operation, sometimes will affect read or write latency. However, compaction currently only has a machine-level counter, we need to add the table-level counter of compaction.

**Comment by acelyc111** [comment]
@Shuo-Jia why close this issue? could you add some description?

**Comment by Shuo-Jia** [comment]
#806 resolved
