### ISSUE TITLE
Bug: Rocksdb flush callback function onFlushCompleted not triggered 

### ISSUE THREAD

**Issue by hycdong** [apache/incubator-pegasus#745]
## Bug Report
Since Pegasus 2.0.0, we found that rocksdb flush related per-counter is invalid, the value of them are always be 0. 
I did lots of manual tests to reproduce the bug, finally found out that the rocksdb flush callback function `onFlushCompleted` was not triggered if rocksdb option `atomic_flush` is true. The rocksdb version is 6.6.4, I had read related code roughly and had no idea about the bug, and I didn't find any information about this bug in rocksdb issues.
To fix this bug, Pegasus might should modify rocksdb related code and pay attend to about it in recent rocksdb release version.

**Comment by zhangyifan27** [comment]
Trace this bug in https://github.com/facebook/rocksdb/issues/8495

**Comment by zhangyifan27** [comment]
Fixed in https://github.com/facebook/rocksdb/commit/0879c240404b00142ba4718f36cd3f2bd537192d, maybe this commit should be cherry-picked into https://github.com/XiaoMi/pegasus-rocksdb or upgrade pegasus-rocksdb to a newer version including this fix.

**Comment by empiredan** [comment]
@hycdong @zhangyifan27 thanks for your work on this bug !

Have we had a plan about the future work ? Since flush-related counters are important for us to analyze the performance problem.

**Comment by empiredan** [comment]
https://github.com/facebook/rocksdb/commit/0879c240404b00142ba4718f36cd3f2bd537192d has been cherry-picked int o pegasus-rocksdb as https://github.com/XiaoMi/pegasus-rocksdb/pull/34
