### ISSUE TITLE
ut：meta server core，when recovery debug ut execute

### ISSUE THREAD

**Issue by Arsenal821** [apache/incubator-pegasus#827]
after `./run.sh test` on type debug system program，I failed at recovery test.
![wecom-temp-bb6a04fa3098e75073cdb475d55cbeab](https://user-images.githubusercontent.com/48315319/137444617-73b28598-67b1-48f9-adeb-ab726b4f5feb.png)
meta server core msg
![image](https://user-images.githubusercontent.com/48315319/137449947-bdd1c7bb-c4a4-4332-ad1f-c7581ac893a2.png)

And then I add some message logs，I find field "duplicating" on struct app_info is null when I create a table.I am not sure what happened between create table and recovery, But I think the initial value should be false.
After set "duplicating"=false for app_info on file rdsn/src/dsn.layer2.thrift, ut passed.
diff struct app_info init code:
![wecom-temp-aaf4b0eea7d821ebccac06b00b40bfda](https://user-images.githubusercontent.com/48315319/137450021-70cd01da-cafd-4c30-acb3-268b32ff917e.png)

**Comment by levy5307** [comment]
Fixed at https://github.com/XiaoMi/rdsn/pull/976
