### ISSUE TITLE
how to handle meta server update failure?

### ISSUE THREAD

**Issue by MoonShining** [apache/incubator-pegasus#838]
hi i have several questions about how pegasus handle some corner case

![image](https://user-images.githubusercontent.com/8097849/141746001-0ea75ac5-d106-427f-8de6-5a9424f745cc.png)

how pegasus handle meta server update failure in step4?， just retry forever？

**Comment by hycdong** [comment]
This step4 is for meta server to update new PartitionConfiguration into zk. If meta server failed to store metadata, its operation will depend on the error. If the error is timeout, it will retry, otherwise, meta server will kill itself and restart. In current design, zk is considered as a stable and reliable component, stores cluster metadata.

**Comment by MoonShining** [comment]
@hycdong thanks for your explanation

another question is,  in step3 primary will send new config to metaserver, what to do if send fail? maybe kill primay itself?

**Comment by hycdong** [comment]
In pegasus, the leader vote is handled by meta server, meaning which replica is primary and which is secondary is determined by meta server, not the replica group. 
In step2, primary will try to downgrade itself, and it will send a downgrade request to meta server, after that its status is not primary, but a status called inactive. Then, the meta server will choose a suitable secondary and a new primary. And then, meta server will send proposal to vote primary and add secondary to let replica group healthy(1 primary and 2 secondaries). 
The word in the picture simplifies the process, the request sent to meta is actually NOT the new PartitionConfiguration without the failed secondary, but the request downgrade primary itself. And if the primary failed while sending request, it doesn't matter, and meta server will know this replica group unhealthy in other ways. 
Hoping my answer helps you.

**Comment by MoonShining** [comment]
thx
