### ISSUE TITLE
build sample of c++ client 2.1.0 failed

### ISSUE THREAD

**Issue by yanz0920** [apache/incubator-pegasus#841]
## Bug Report

Following the instructions in https://pegasus.apache.org/docs/build/compile-from-source/, I have build the pegasus successfully. BUT, I failed in building the sample in  pegasus-client-2.1.0-non-git-glibc2.27-release/sample, here is the outputs:

../lib/libpegasus_client_static.a(pegasus_client_impl.cpp.o): In function `pegasus::client::pegasus_client_impl::get_error_string(int) const':
/software/apache-pegasus-2.1.0-incubating-src/src/client_lib/pegasus_client_impl.cpp:1272: undefined reference to `dsn_log_start_level'
/software/apache-pegasus-2.1.0-incubating-src/src/client_lib/pegasus_client_impl.cpp:1272: undefined reference to `dsn_logf(char const*, char const*, int, dsn_log_level_t, char const*, ...)'
/software/apache-pegasus-2.1.0-incubating-src/src/client_lib/pegasus_client_impl.cpp:1272: undefined reference to `dsn_logf(char const*, char const*, int, dsn_log_level_t, char const*, ...)'
../lib/libpegasus_client_static.a(pegasus_client_impl.cpp.o): In function `pegasus::client::pegasus_client_impl::get_client_error(int)':
/software/apache-pegasus-2.1.0-incubating-src/src/client_lib/pegasus_client_impl.cpp:1310: undefined reference to `dsn_log_start_level'
/software/apache-pegasus-2.1.0-incubating-src/src/client_lib/pegasus_client_impl.cpp:1310: undefined reference to `dsn::error_code::to_string() const'
/software/apache-pegasus-2.1.0-incubating-src/src/client_lib/pegasus_client_impl.cpp:1310: undefined reference to `dsn_logf(char const*, char const*, int, dsn_log_level_t, char const*, ...)'
../lib/libpegasus_client_static.a(pegasus_client_impl.cpp.o): In function `pegasus::client::pegasus_client_impl::get_scanner(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, pegasus::pegasus_client::scan_options const&, pegasus::pegasus_client::pegasus_scanner*&)':
/software/apache-pegasus-2.1.0-incubating-src/src/client_lib/pegasus_client_impl.cpp:1136: undefined reference to `dsn_log_start_level'
/software/apache-pegasus-2.1.0-incubating-src/src/client_lib/pegasus_client_impl.cpp:1141: undefined reference to `dsn_log_start_level'
/software/apache-pegasus-2.1.0-incubating-src/src/client_lib/pegasus_client_impl.cpp:1141: undefined reference to `dsn_logf(char const*, char const*, int, dsn_log_level_t, char const*, ...)'
/software/apache-pegasus-2.1.0-incubating-src/src/client_lib/pegasus_client_impl.cpp:1136: undefined reference to `dsn_logf(char const*, char const*, int, dsn_log_level_t, char const*, ...)'
../lib/libpegasus_client_static.a(pegasus_client_impl.cpp.o): In function `pegasus::client::pegasus_client_impl::async_duplicate(dsn::rpc_holder<dsn::apps::duplicate_request, dsn::apps::duplicate_response>, std::function<void (dsn::error_code)>&&, dsn::task_tracker*)':
/software/apache-pegasus-2.1.0-incubating-src/DSN_ROOT/include/dsn/cpp/rpc_holder.h:128: undefined reference to `dsn_log_start_level'
/software/apache-pegasus-2.1.0-incubating-src/DSN_ROOT/include/dsn/cpp/rpc_holder.h:128: undefined reference to `dsn_logf(char const*, char const*, int, dsn_log_level_t, char const*, ...)'
/software/apache-pegasus-2.1.0-incubating-src/DSN_ROOT/include/dsn/cpp/rpc_holder.h:128: undefined reference to `dsn_logf(char const*, char const*, int, dsn_log_level_t, char const*, ...)'
../lib/libpegasus_client_static.a(pegasus_client_impl.cpp.o): In function `pegasus::client::pegasus_client_impl::pegasus_client_impl(char const*, char const*)':
/software/apache-pegasus-2.1.0-incubating-src/src/client_lib/pegasus_client_impl.cpp:51: undefined reference to `dsn::rpc_address::assign_group(char const*)'
../lib/libpegasus_client_static.a(pegasus_client_impl.cpp.o): In function `pegasus::client::pegasus_client_impl::pegasus_client_impl(char const*, char const*)':
/software/apache-pegasus-2.1.0-incubating-src/DSN_ROOT/include/dsn/tool-api/group_address.h:57: undefined reference to `dsn::rpc_address::~rpc_address()'
/software/apache-pegasus-2.1.0-incubating-src/DSN_ROOT/include/dsn/tool-api/group_address.h:57: undefined reference to `dsn::rpc_address::rpc_address(dsn::rpc_address const&)'
../lib/libpegasus_client_static.a(pegasus_client_impl.cpp.o): In function `pegasus::client::pegasus_client_impl::pegasus_client_impl(char const*, char const*)':
/usr/include/c++/7/ext/new_allocator.h:136: undefined reference to `dsn::rpc_address::rpc_address(dsn::rpc_address const&)'
...

**Comment by acelyc111** [comment]
The master branch has added `sample` as a subdirectory, and will be built everyday on various of plats. I'll close this issue, you can reopen it if you find the master branch build it failed, thanks.
