### ISSUE TITLE
build problem when using toolchain

### ISSUE THREAD

**Issue by qinzuoyan** [apache/incubator-pegasus#86]
在build机器上使用toolchain进行编译时，我发现：
如果环境变量设置了：
```
export LIBRARY_PATH="$DSN_THIRDPARTY_ROOT/lib"
``` 
那么CMakeLists.txt中的以下语句不会生效：
```
link_directories(${DSN_THIRDPARTY_ROOT}/lib)
```
造成的后果就是```${DSN_THIRDPARTY_ROOT}/lib```不在链接的-L路径里面，链接时因为找不到库或者找到错误的库，链接失败。

搜到一些可能相关的链接： https://public.kitware.com/Bug/view.php?id=16074

**Comment by qinzuoyan** [comment]
感觉其实与是否toolchain没有关系，在普通环境下也可重现：
```
export LIBRARY_PATH=`pwd`/rdsn/thirdparty/output/lib
./run.sh build -c -v
```

**Comment by vagetablechicken** [comment]
我也测试了一下，现在是gflags库链接错误，不过问题本质相同。
原因应该是：export LIBRARY_PATH使得thirdparty的路径变成了gcc认为的“系统路径”，link_directories(${DSN_THIRDPARTY_ROOT}/lib)就是在重复link“系统路径”，于是cmake出来的link就不会-L thirdparty。
用下面的CMakeLists.txt测试
```
cmake_minimum_required(VERSION 3.11)

set(MY_PROJ_NAME "test")
project(${MY_PROJ_NAME} C CXX)

set(MY_PROJ_SRC main.cpp)
set(MY_SRC_SEARCH_MODE "GLOB")

link_directories(/home/huangwei5/export/pegasus/rdsn/thirdparty/output/lib)

add_executable(${MY_PROJ_NAME} ${MY_PROJ_SRC})

target_link_libraries(${MY_PROJ_NAME} gflags)
```
生成的link.txt为：
`/usr/bin/c++     CMakeFiles/test.dir/main.cpp.o  -o test -lgflags `

而实际链接的是系统路径下的库/usr/lib/xxx这个的原因，是因为export的LIBRARY_PATH，在gcc那里是被处理过的，通过gcc/g++ --print-search-dirs可以得到：
libraries: =**/home/huangwei5/export/pegasus/rdsn/thirdparty/output/lib**/x86_64-redhat-linux/4.8.5/:**/home/huangwei5/export/pegasus/rdsn/thirdparty/output/lib/**../lib64/:/usr/lib/gcc/x86_64-redhat-linux/4.8.5/:/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../x86_64-redhat-linux/lib/x86_64-redhat-linux/4.8.5/:/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../x86_64-redhat-linux/lib/../lib64/:/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../x86_64-redhat-linux/4.8.5/:/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/:/lib/x86_64-redhat-linux/4.8.5/:/lib/../lib64/:/usr/lib/x86_64-redhat-linux/4.8.5/:/usr/lib/../lib64/:**/home/huangwei5/export/pegasus/rdsn/thirdparty/output/lib/**:/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../x86_64-redhat-linux/lib/:/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../:/lib/:/usr/lib/

可以看出，/home/huangwei5/export/pegasus/rdsn/thirdparty/output/lib/这个正确的路径优先级很低，低于/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64，其实也就是/usr/lib64这个路径。

**Comment by vagetablechicken** [comment]
这种问题本质是不指定库的绝对路径导致的，cmake在高版本里也非常提倡使用绝对路径。头文件和库的匹配还是通过find_package来解决比较好，也简单明了。
所以我打算修改下编译脚本，不再使用link_directories()，顺便可以把高版本gcc编译时的语法问题也修一下。
