### ISSUE TITLE
Feature: support to get/set the replication factor of each table

### ISSUE THREAD

**Issue by empiredan** [apache/incubator-pegasus#865]
# 1. Motivation

Replication factor (RF), is the number of nodes (i.e. replica servers) where each partition of a table is replicated. In Apache Pegasus, we also call it *max replica count* or *replica count*.

Initially, the minimum RF was 3; Then, in order to reduce the cost for our users, in https://github.com/XiaoMi/rdsn/pull/932 we've supported RF=1 and RF=2, though it's not reliable enough for most distributed systems while RF is 1 or 2. 

In other words, the minimum RF has become 1. Imagine a scenario that we had 2 replica servers in a cluster where a table can only be created with RF=1 or RF=2. As the volume of data continues to grow, the capacity of  this cluster is not enough; Also, it's not scalable and reliable for the 2 replica servers.

Now we would add another 2 nodes into this cluster and increase the RF of each table to 3 to improve the reliability and scalability. Therefore, besides that RF is specified while creating table, it should be changeable after the table is created. To make RF settable dynamically, appropriate commands should be added into the management tool such as Pegasus Shell to query or update the RF.

# 2. Limitation

Previously we've restricted the RF while creating table in https://github.com/XiaoMi/rdsn/pull/963. These restriction rules will also be applied as the prerequisites before the RF could be updated successfully.

# 3. Usage

As is described above, the RF could be queried or updated by Pegasus Shell. Here is the patterns of the commands.

It should be noted that to follow the naming convention in Pegasus, `replica count` is used in the command to represent the RF.

## 3.1 Query the RF

```shell
get_replica_count <table_name>
```

After this command is executed, the RF of the specified table will be printed if it's successful; Otherwise the error will be printed.

## 3.2 Update the RF

```shell
set_replica_count <table_name> <replica_count>
```

Since this command will update the RF of a table, in case of incorrect operations a prompt will be printed immediately after the command is executed to ask if the administrator chooses to continue to update the RF. Then, it will tell the command is finished successfully, or, similarly with `get_replica_count`,  the error will be printed.

# 4. Implementation

Here we only illustrate the process of `set_replica_count`, since `get_replica_count` is quite simple.

## 4.1 Basic process

The whole process contains the following steps:
* Administrator inputs and confirms `set_replica_count` command by Pegasus Shell;
* The `set_replica_count` request is sent to Primary Meta Server;
* Meta Server checks whether the requested RF is valid, whether the table exists, etc.;
* Meta Server sets an environment variable for the table in case a duplicate request is processed;
* Meta Server submits to ZooKeeper to change the meta data;
* Meta Server repairs the number of replicas of the specified table to reach the target RF.

As the saying goes, "A picture is worth a thousand words". The process described above can be illustrated as the following sequence diagram:
![image](https://user-images.githubusercontent.com/743379/148215462-2ac493a3-df6c-4eb4-a273-67c2b7c90295.png)

Obviously it's showed in the sequence diagram that:
* Both partition-level and table-level meta data should be updated, with partition-levels first and table-level successively;
* Each partition is set one by one, and all the meta data are updated asynchronously.

As for the 2 levels of meta data, see the following section for details.

## 4.2 Set an environment variable to prevent the duplicate requests

After the request that updates RF is issued, however, another duplicate request may also be issued by mistake. Since the whole process that updates RF is not atomic, this may lead to undefined result.

In case the process is disrupted, we can first set an environment variable indicating that RF of the table is being updated. Once then another duplicate request is received, the env is checked first and this request will be rejected.

After the whole process is finished, which means RF has been updated safely, the env will be removed. Then, a new request that update RF can be accepted.

## 4.3 Update the meta data

An example is given here to describe both partition-level and table-level meta data.

Suppose that there is a table named `test2` with id `5`.

First we can list all the tables in the ZooKeeper Shell:
```shell
[zk: localhost:2181(CONNECTED) 5] ls /pegasus_cluster/apps/5
[0, 1, 2, 3, 4, 5, 6, 7]
```

Then, table-level meta data of the target table (id `5`) can be found as below, where `max_replica_count` is the RF to be updated:
```shell
[zk: localhost:2181(CONNECTED) 4] get /pegasus_cluster/apps/5
{"status":"app_status::AS_AVAILABLE","app_type":"pegasus","app_name":"test2","app_id":5,"partition_count":8,"envs":{},"is_stateful":1,"max_replica_count":2,"expire_second":0,"create_second":1611726087,"drop_second":0,"duplicating":0,"init_partition_count":-1}
```

Under table-level is the partition-level meta data showed as below where there is also a `max_replica_count`:
```shell
[zk: localhost:2181(CONNECTED) 3] get /pegasus_cluster/apps/5/0
{"pid":"5.0","ballot":11,"max_replica_count":2,"primary":"10.20.156.227:34801","secondaries":["10.20.156.228:34801"],"last_drops":[],"last_committed_decree":3799,"partition_flags":0}
```

## 4.4 Repair the number of replicas to reach RF

In Meta Server there is some thread in charge of detecting periodically (each `lb_interval_ms`), trying to repair the number of replicas of the table to reach the demanded RF. 

Thus we can draw a conclusion that it will take about `lb_interval_ms` (typically 10s) from when the meta data is updated until the number of replicas is repaired.

# 5. Schedule

This feature has been implemented and tested, then released as the internal version. In the internal release, https://github.com/XiaoMi/rdsn/pull/963 and this feature  are in the same PR. I split the monolithic PR into 2 independent ones:
* The first PR whose purpose is to provide some rules used to check whether an RF is valid, has been committed and merged.
* And another PR will be this feature. 

However there are still some tasks that haven't be done. Previously all of our scenarios are to increase the RF. We haven't tested decreasing the RF. 

Also, after the RF is decreased, there are 2 situations:
* No node is removed, and then the cluster is balanced;
* One or more nodes are removed, then the cluster is balanced.

For both situations, some operations should be tested together as a whole set of steps, such as `scripts/pegasus_offline_node_list.sh`.

Therefore after the unfinished jobs are done, this feature will be committed.

- [x] https://github.com/XiaoMi/rdsn/pull/1061
- [x] https://github.com/XiaoMi/rdsn/pull/1072
- [x] https://github.com/XiaoMi/rdsn/pull/1077
- [x] https://github.com/XiaoMi/rdsn/pull/1087
- [x] https://github.com/XiaoMi/rdsn/pull/1107
- [x] https://github.com/XiaoMi/rdsn/pull/1108
- [x] https://github.com/XiaoMi/rdsn/pull/1109
- [x] https://github.com/XiaoMi/rdsn/pull/1110
- [x] https://github.com/apache/incubator-pegasus/issues/995
- [x] https://github.com/apache/incubator-pegasus/pull/914
- [x] https://github.com/apache/incubator-pegasus/pull/999

**Comment by Smityz** [comment]
Can load balancer help to recover the cluster after RF changes?

**Comment by hycdong** [comment]
Good enhancement~

I have some questions about updating table replica count:
1. There're also cluster-level config called `max_replica_count`, will it be confict if cluster `max_replica_count` is not equal to table `max_replica_count`? Will important features work such as user read/write, learn, load balance, rolling_update?
2. Table `app_info` file will store in each replica disk (_dir/.app_info), if `max_replica_count` is updated, this file should also be updated, how to update it?
3. In your description, `cure` (executed each 10s) will delete redunant replica or add lacking replica. Could you please add some manual test results?

Expecting your reply~

**Comment by levy5307** [comment]
> Can load balancer help to recover the cluster after RF changes?

It has no business with load balance when RF  changed

**Comment by levy5307** [comment]
> Each partition is set one by one, and all the meta data are updated asynchronously.

Does it has problem when each partition and meta data updated asynchronously?  Assuming that we are changing RF from 1 to 3. Because they are updated asynchronously, there will be a moment that partition 0 has 3 replicas and partition 1 has only one replica. Does it work well?

**Comment by empiredan** [comment]
> Good enhancement~
> 
> I have some questions about updating table replica count:
> 
> 1. There're also cluster-level config called `max_replica_count`, will it be confict if cluster `max_replica_count` is not equal to table `max_replica_count`? Will important features work such as user read/write, learn, load balance, rolling_update?
> 2. Table `app_info` file will store in each replica disk (_dir/.app_info), if `max_replica_count` is updated, this file should also be updated, how to update it?
> 3. In your description, `cure` (executed each 10s) will delete redunant replica or add lacking replica. Could you please add some manual test results?
> 
> Expecting your reply~

Ok, let's discuss one by one:
1.  Does cluster-level config mean `max_allowed_replica_count` in https://github.com/XiaoMi/rdsn/pull/963 ? Actually `max_replica_count` is the RF, and `max_allowed_replica_count` is a the upper bound to which an RF can be set. Or we should rename `max_replica_count` as replication_factor to avoid misunderstanding ?
2. Good question ! This implementation has't written into `.app_info`, this is a bug ! To guarantee the atomicity, I think first the request `set_replica_count` can be replicated to each replica; Received the request, each replica writes it into `slog`, and then writes the new `max_replica_count` into `.app_info`. Even if a replica server fails during the process, the request will not be lost.
3. As is described in this issue, increasing `max_replica_count` has been tested sufficiently, however decreasing `max_replica_count` has not been tested. I'll test decreasing later to see if redundant replica can be processed correctly.

**Comment by empiredan** [comment]
> > Can load balancer help to recover the cluster after RF changes?
> 
> It has no business with load balance when RF changed

Yeah, as @levy5307 has said, I can explain this.

Actually `set_replica_count` just sets the meta data held by ZooKeeper. The number of replicas is repaired by `cure`, which is also mentioned by @hycdong.

For example, if we want to increase `max_replica_count`, say, from 2 to 3. A secondary should be added to reach RF 3. If  there's no dropped node, it will be added by `emergency`; Otherwise, a dropped node will be selected to deploy the replica. For details please see `partition_guardian::on_missing_secondary`.

**Comment by empiredan** [comment]
> > Each partition is set one by one, and all the meta data are updated asynchronously.
> 
> Does it has problem when each partition and meta data updated asynchronously? Assuming that we are changing RF from 1 to 3. Because they are updated asynchronously, there will be a moment that partition 0 has 3 replicas and partition 1 has only one replica. Will it work well?

This is a problem of atomicity as has been discussed with @hycdong . Actually all the table-level and partition-level meta data, together with `.app_info` should be updated in a "transaction". Unfortunately, the whole process is not atomic except that we can introduce a mechanism to guarantee all the operations can be managed in a way of transaction.

However, in practice the update process of all meta data is very fast, usually finished within a second.

**Comment by hycdong** [comment]
> > Good enhancement~
> > I have some questions about updating table replica count:
> > 
> > 1. There're also cluster-level config called `max_replica_count`, will it be confict if cluster `max_replica_count` is not equal to table `max_replica_count`? Will important features work such as user read/write, learn, load balance, rolling_update?
> > 2. Table `app_info` file will store in each replica disk (_dir/.app_info), if `max_replica_count` is updated, this file should also be updated, how to update it?
> > 3. In your description, `cure` (executed each 10s) will delete redunant replica or add lacking replica. Could you please add some manual test results?
> > 
> > Expecting your reply~
> 
> Ok, let's discuss one by one:
> 
> 1. Does cluster-level config mean `max_allowed_replica_count` in [feat: restrict the replication factor while creating app XiaoMi/rdsn#963](https://github.com/XiaoMi/rdsn/pull/963) ? Actually `max_replica_count` is the RF, and `max_allowed_replica_count` is a the upper bound to which an RF can be set. Or we should rename `max_replica_count` as replication_factor to avoid misunderstanding ?
> 2. Good question ! This implementation has't written into `.app_info`, this is a bug ! To guarantee the atomicity, I think first the request `set_replica_count` can be replicated to each replica; Received the request, each replica writes it into `slog`, and then writes the new `max_replica_count` into `.app_info`. Even if a replica server fails during the process, the request will not be lost.
> 3. As is described in this issue, increasing `max_replica_count` has been tested sufficiently, however decreasing `max_replica_count` has not been tested. I'll test decreasing later to see if redundant replica can be processed correctly.

Thanks for your reply~ Continue to discuss:
1.  I mean meta option called `max_replicas_in_group` , you can reference it here:
https://github.com/XiaoMi/rdsn/blob/289eb4609ae781e3bcc6bbc6bfeae64dfd8fa785/src/meta/meta_options.cpp#L160-L161
2.  I suggest that you can update `max_replica_count` through `on_config_sync` into `.app_info`
3.  I think decreasing replica count may have some problems, expecting your test result~

**Comment by empiredan** [comment]
> > > Good enhancement~
> > > I have some questions about updating table replica count:
> > > 
> > > 1. There're also cluster-level config called `max_replica_count`, will it be confict if cluster `max_replica_count` is not equal to table `max_replica_count`? Will important features work such as user read/write, learn, load balance, rolling_update?
> > > 2. Table `app_info` file will store in each replica disk (_dir/.app_info), if `max_replica_count` is updated, this file should also be updated, how to update it?
> > > 3. In your description, `cure` (executed each 10s) will delete redunant replica or add lacking replica. Could you please add some manual test results?
> > > 
> > > Expecting your reply~
> > 
> > 
> > Ok, let's discuss one by one:
> > 
> > 1. Does cluster-level config mean `max_allowed_replica_count` in [feat: restrict the replication factor while creating app XiaoMi/rdsn#963](https://github.com/XiaoMi/rdsn/pull/963) ? Actually `max_replica_count` is the RF, and `max_allowed_replica_count` is a the upper bound to which an RF can be set. Or we should rename `max_replica_count` as replication_factor to avoid misunderstanding ?
> > 2. Good question ! This implementation has't written into `.app_info`, this is a bug ! To guarantee the atomicity, I think first the request `set_replica_count` can be replicated to each replica; Received the request, each replica writes it into `slog`, and then writes the new `max_replica_count` into `.app_info`. Even if a replica server fails during the process, the request will not be lost.
> > 3. As is described in this issue, increasing `max_replica_count` has been tested sufficiently, however decreasing `max_replica_count` has not been tested. I'll test decreasing later to see if redundant replica can be processed correctly.
> 
> Thanks for your reply~ Continue to discuss:
> 
> 1. I mean meta option called `max_replicas_in_group` , you can reference it here:
>    https://github.com/XiaoMi/rdsn/blob/289eb4609ae781e3bcc6bbc6bfeae64dfd8fa785/src/meta/meta_options.cpp#L160-L161
> 2. I suggest that you can update `max_replica_count` through `on_config_sync` into `.app_info`
> 3. I think decreasing replica count may have some problems, expecting your test result~

Thanks for suggestion !

1. I think we can eliminate `max_replicas_in_group` and turn to partition-level `max_replica_count`. I'll explain this as below:

Now `max_replicas_in_group` is only used to update `config_context::MAX_REPLICA_COUNT_IN_GRROUP`; And `config_context::MAX_REPLICA_COUNT_IN_GRROUP` is only used in:
```c++
void config_context::check_size()
{
    // when add learner, it is possible that replica_count > max_replica_count, so we
    // need to remove things from dropped only when it's not empty.
    while (replica_count(*config_owner) + dropped.size() > MAX_REPLICA_COUNT_IN_GRROUP &&
           !dropped.empty()) {
        dropped.erase(dropped.begin());
        prefered_dropped = (int)dropped.size() - 1;
    }
}
```

However, `MAX_REPLICA_COUNT_IN_GRROUP` can be replaced with partition-level `max_replica_count` as below:

```c++
void config_context::check_size()
{
    // when add learner, it is possible that replica_count > max_replica_count, so we
    // need to remove things from dropped only when it's not empty.
    while (replica_count(*config_owner) + dropped.size() > config_owner->max_replica_count &&
           !dropped.empty()) {
        dropped.erase(dropped.begin());
        prefered_dropped = (int)dropped.size() - 1;
    }
}
```

The `partition_configuration` pointed by `config_owner` is updated in `server_state::on_update_configuration_on_remote_reply`, which will be called by `set_replica_count`.
 
2. Good idea ! Each `config_sync_interval_ms` (typically 30 ms) the replica server requests `query_configuration_by_node` to the meta server; Received the response, if the ballot of the response is newer than the local, the replica server will update every table-level and partition-level `max_replica_count` to the one of the response. Is it right ?

3. Actually decreasing replica count has been forbidden till now by us. Decreasing is more error-prone than increasing. If we decide to support decreasing replica count, I'll test sufficiently.

**Comment by hycdong** [comment]
> > > > Good enhancement~
> > > > I have some questions about updating table replica count:
> > > > 
> > > > 1. There're also cluster-level config called `max_replica_count`, will it be confict if cluster `max_replica_count` is not equal to table `max_replica_count`? Will important features work such as user read/write, learn, load balance, rolling_update?
> > > > 2. Table `app_info` file will store in each replica disk (_dir/.app_info), if `max_replica_count` is updated, this file should also be updated, how to update it?
> > > > 3. In your description, `cure` (executed each 10s) will delete redunant replica or add lacking replica. Could you please add some manual test results?
> > > > 
> > > > Expecting your reply~
> > > 
> > > 
> > > Ok, let's discuss one by one:
> > > 
> > > 1. Does cluster-level config mean `max_allowed_replica_count` in [feat: restrict the replication factor while creating app XiaoMi/rdsn#963](https://github.com/XiaoMi/rdsn/pull/963) ? Actually `max_replica_count` is the RF, and `max_allowed_replica_count` is a the upper bound to which an RF can be set. Or we should rename `max_replica_count` as replication_factor to avoid misunderstanding ?
> > > 2. Good question ! This implementation has't written into `.app_info`, this is a bug ! To guarantee the atomicity, I think first the request `set_replica_count` can be replicated to each replica; Received the request, each replica writes it into `slog`, and then writes the new `max_replica_count` into `.app_info`. Even if a replica server fails during the process, the request will not be lost.
> > > 3. As is described in this issue, increasing `max_replica_count` has been tested sufficiently, however decreasing `max_replica_count` has not been tested. I'll test decreasing later to see if redundant replica can be processed correctly.
> > 
> > 
> > Thanks for your reply~ Continue to discuss:
> > 
> > 1. I mean meta option called `max_replicas_in_group` , you can reference it here:
> >    https://github.com/XiaoMi/rdsn/blob/289eb4609ae781e3bcc6bbc6bfeae64dfd8fa785/src/meta/meta_options.cpp#L160-L161
> > 2. I suggest that you can update `max_replica_count` through `on_config_sync` into `.app_info`
> > 3. I think decreasing replica count may have some problems, expecting your test result~
> 
> Thanks for suggestion !
> 
> 1. I think we can eliminate `max_replicas_in_group` and turn to partition-level `max_replica_count`. I'll explain this as below:
> 
> Now `max_replicas_in_group` is only used to update `config_context::MAX_REPLICA_COUNT_IN_GRROUP`; And `config_context::MAX_REPLICA_COUNT_IN_GRROUP` is only used in:
> 
> ```c++
> void config_context::check_size()
> {
>     // when add learner, it is possible that replica_count > max_replica_count, so we
>     // need to remove things from dropped only when it's not empty.
>     while (replica_count(*config_owner) + dropped.size() > MAX_REPLICA_COUNT_IN_GRROUP &&
>            !dropped.empty()) {
>         dropped.erase(dropped.begin());
>         prefered_dropped = (int)dropped.size() - 1;
>     }
> }
> ```
> 
> However, `MAX_REPLICA_COUNT_IN_GRROUP` can be replaced with partition-level `max_replica_count` as below:
> 
> ```c++
> void config_context::check_size()
> {
>     // when add learner, it is possible that replica_count > max_replica_count, so we
>     // need to remove things from dropped only when it's not empty.
>     while (replica_count(*config_owner) + dropped.size() > config_owner->max_replica_count &&
>            !dropped.empty()) {
>         dropped.erase(dropped.begin());
>         prefered_dropped = (int)dropped.size() - 1;
>     }
> }
> ```
> 
> The `partition_configuration` pointed by `config_owner` is updated in `server_state::on_update_configuration_on_remote_reply`, which will be called by `set_replica_count`.
> 
> 2. Good idea ! Each `config_sync_interval_ms` (typically 30 ms) the replica server requests `query_configuration_by_node` to the meta server; Received the response, if the ballot of the response is newer than the local, the replica server will update every table-level and partition-level `max_replica_count` to the one of the response. Is it right ?
> 3. Actually decreasing replica count has been forbidden till now by us. Decreasing is more error-prone than increasing. If we decide to support decreasing replica count, I'll test sufficiently.

Thanks for your reply~
1. If you have already checked that table level replica_count can replace cluster `max_replicas_in_group`, just go ahead~
2. Yes, I recommend update `.app_info` file through `on_config_sync` rpc
3. Okay. How about update this issue title from `update the replication factor` into `increase the replication factor`? As the decreasing is not supported.

**Comment by empiredan** [comment]
> > > > > Good enhancement~
> > > > > I have some questions about updating table replica count:
> > > > > 
> > > > > 1. There're also cluster-level config called `max_replica_count`, will it be confict if cluster `max_replica_count` is not equal to table `max_replica_count`? Will important features work such as user read/write, learn, load balance, rolling_update?
> > > > > 2. Table `app_info` file will store in each replica disk (_dir/.app_info), if `max_replica_count` is updated, this file should also be updated, how to update it?
> > > > > 3. In your description, `cure` (executed each 10s) will delete redunant replica or add lacking replica. Could you please add some manual test results?
> > > > > 
> > > > > Expecting your reply~
> > > > 
> > > > 
> > > > Ok, let's discuss one by one:
> > > > 
> > > > 1. Does cluster-level config mean `max_allowed_replica_count` in [feat: restrict the replication factor while creating app XiaoMi/rdsn#963](https://github.com/XiaoMi/rdsn/pull/963) ? Actually `max_replica_count` is the RF, and `max_allowed_replica_count` is a the upper bound to which an RF can be set. Or we should rename `max_replica_count` as replication_factor to avoid misunderstanding ?
> > > > 2. Good question ! This implementation has't written into `.app_info`, this is a bug ! To guarantee the atomicity, I think first the request `set_replica_count` can be replicated to each replica; Received the request, each replica writes it into `slog`, and then writes the new `max_replica_count` into `.app_info`. Even if a replica server fails during the process, the request will not be lost.
> > > > 3. As is described in this issue, increasing `max_replica_count` has been tested sufficiently, however decreasing `max_replica_count` has not been tested. I'll test decreasing later to see if redundant replica can be processed correctly.
> > > 
> > > 
> > > Thanks for your reply~ Continue to discuss:
> > > 
> > > 1. I mean meta option called `max_replicas_in_group` , you can reference it here:
> > >    https://github.com/XiaoMi/rdsn/blob/289eb4609ae781e3bcc6bbc6bfeae64dfd8fa785/src/meta/meta_options.cpp#L160-L161
> > > 2. I suggest that you can update `max_replica_count` through `on_config_sync` into `.app_info`
> > > 3. I think decreasing replica count may have some problems, expecting your test result~
> > 
> > 
> > Thanks for suggestion !
> > 
> > 1. I think we can eliminate `max_replicas_in_group` and turn to partition-level `max_replica_count`. I'll explain this as below:
> > 
> > Now `max_replicas_in_group` is only used to update `config_context::MAX_REPLICA_COUNT_IN_GRROUP`; And `config_context::MAX_REPLICA_COUNT_IN_GRROUP` is only used in:
> > ```c++
> > void config_context::check_size()
> > {
> >     // when add learner, it is possible that replica_count > max_replica_count, so we
> >     // need to remove things from dropped only when it's not empty.
> >     while (replica_count(*config_owner) + dropped.size() > MAX_REPLICA_COUNT_IN_GRROUP &&
> >            !dropped.empty()) {
> >         dropped.erase(dropped.begin());
> >         prefered_dropped = (int)dropped.size() - 1;
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > However, `MAX_REPLICA_COUNT_IN_GRROUP` can be replaced with partition-level `max_replica_count` as below:
> > ```c++
> > void config_context::check_size()
> > {
> >     // when add learner, it is possible that replica_count > max_replica_count, so we
> >     // need to remove things from dropped only when it's not empty.
> >     while (replica_count(*config_owner) + dropped.size() > config_owner->max_replica_count &&
> >            !dropped.empty()) {
> >         dropped.erase(dropped.begin());
> >         prefered_dropped = (int)dropped.size() - 1;
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The `partition_configuration` pointed by `config_owner` is updated in `server_state::on_update_configuration_on_remote_reply`, which will be called by `set_replica_count`.
> > 
> > 2. Good idea ! Each `config_sync_interval_ms` (typically 30 ms) the replica server requests `query_configuration_by_node` to the meta server; Received the response, if the ballot of the response is newer than the local, the replica server will update every table-level and partition-level `max_replica_count` to the one of the response. Is it right ?
> > 3. Actually decreasing replica count has been forbidden till now by us. Decreasing is more error-prone than increasing. If we decide to support decreasing replica count, I'll test sufficiently.
> 
> Thanks for your reply~
> 
> 1. If you have already checked that table level replica_count can replace cluster `max_replicas_in_group`, just go ahead~
> 2. Yes, I recommend update `.app_info` file through `on_config_sync` rpc
> 3. Okay. How about update this issue title from `update the replication factor` into `increase the replication factor`? As the decreasing is not supported.

Ok, we can first support increasing the replication factor. Decreasing can be supported later if needed.

**Comment by levy5307** [comment]
> > > > > > Good enhancement~
> > > > > > I have some questions about updating table replica count:
> > > > > > 
> > > > > > 1. There're also cluster-level config called `max_replica_count`, will it be confict if cluster `max_replica_count` is not equal to table `max_replica_count`? Will important features work such as user read/write, learn, load balance, rolling_update?
> > > > > > 2. Table `app_info` file will store in each replica disk (_dir/.app_info), if `max_replica_count` is updated, this file should also be updated, how to update it?
> > > > > > 3. In your description, `cure` (executed each 10s) will delete redunant replica or add lacking replica. Could you please add some manual test results?
> > > > > > 
> > > > > > Expecting your reply~
> > > > > 
> > > > > 
> > > > > Ok, let's discuss one by one:
> > > > > 
> > > > > 1. Does cluster-level config mean `max_allowed_replica_count` in [feat: restrict the replication factor while creating app XiaoMi/rdsn#963](https://github.com/XiaoMi/rdsn/pull/963) ? Actually `max_replica_count` is the RF, and `max_allowed_replica_count` is a the upper bound to which an RF can be set. Or we should rename `max_replica_count` as replication_factor to avoid misunderstanding ?
> > > > > 2. Good question ! This implementation has't written into `.app_info`, this is a bug ! To guarantee the atomicity, I think first the request `set_replica_count` can be replicated to each replica; Received the request, each replica writes it into `slog`, and then writes the new `max_replica_count` into `.app_info`. Even if a replica server fails during the process, the request will not be lost.
> > > > > 3. As is described in this issue, increasing `max_replica_count` has been tested sufficiently, however decreasing `max_replica_count` has not been tested. I'll test decreasing later to see if redundant replica can be processed correctly.
> > > > 
> > > > 
> > > > Thanks for your reply~ Continue to discuss:
> > > > 
> > > > 1. I mean meta option called `max_replicas_in_group` , you can reference it here:
> > > >    https://github.com/XiaoMi/rdsn/blob/289eb4609ae781e3bcc6bbc6bfeae64dfd8fa785/src/meta/meta_options.cpp#L160-L161
> > > > 2. I suggest that you can update `max_replica_count` through `on_config_sync` into `.app_info`
> > > > 3. I think decreasing replica count may have some problems, expecting your test result~
> > > 
> > > 
> > > Thanks for suggestion !
> > > 
> > > 1. I think we can eliminate `max_replicas_in_group` and turn to partition-level `max_replica_count`. I'll explain this as below:
> > > 
> > > Now `max_replicas_in_group` is only used to update `config_context::MAX_REPLICA_COUNT_IN_GRROUP`; And `config_context::MAX_REPLICA_COUNT_IN_GRROUP` is only used in:
> > > ```c++
> > > void config_context::check_size()
> > > {
> > >     // when add learner, it is possible that replica_count > max_replica_count, so we
> > >     // need to remove things from dropped only when it's not empty.
> > >     while (replica_count(*config_owner) + dropped.size() > MAX_REPLICA_COUNT_IN_GRROUP &&
> > >            !dropped.empty()) {
> > >         dropped.erase(dropped.begin());
> > >         prefered_dropped = (int)dropped.size() - 1;
> > >     }
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > However, `MAX_REPLICA_COUNT_IN_GRROUP` can be replaced with partition-level `max_replica_count` as below:
> > > ```c++
> > > void config_context::check_size()
> > > {
> > >     // when add learner, it is possible that replica_count > max_replica_count, so we
> > >     // need to remove things from dropped only when it's not empty.
> > >     while (replica_count(*config_owner) + dropped.size() > config_owner->max_replica_count &&
> > >            !dropped.empty()) {
> > >         dropped.erase(dropped.begin());
> > >         prefered_dropped = (int)dropped.size() - 1;
> > >     }
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > The `partition_configuration` pointed by `config_owner` is updated in `server_state::on_update_configuration_on_remote_reply`, which will be called by `set_replica_count`.
> > > 
> > > 2. Good idea ! Each `config_sync_interval_ms` (typically 30 ms) the replica server requests `query_configuration_by_node` to the meta server; Received the response, if the ballot of the response is newer than the local, the replica server will update every table-level and partition-level `max_replica_count` to the one of the response. Is it right ?
> > > 3. Actually decreasing replica count has been forbidden till now by us. Decreasing is more error-prone than increasing. If we decide to support decreasing replica count, I'll test sufficiently.
> > 
> > 
> > Thanks for your reply~
> > 
> > 1. If you have already checked that table level replica_count can replace cluster `max_replicas_in_group`, just go ahead~
> > 2. Yes, I recommend update `.app_info` file through `on_config_sync` rpc
> > 3. Okay. How about update this issue title from `update the replication factor` into `increase the replication factor`? As the decreasing is not supported.
> 
> Ok, we can first support increasing the replication factor. Decreasing can be supported later if needed.

I aggree with you about renaming `max_replica_count` to `replication_factor` : )

**Comment by levy5307** [comment]
Besides, I agree with you about removing `max_replicas_in_group`, but we should keep config_context::MAX_REPLICA_COUNT_IN_GRROUP as partition-level `max_replica_count` + 1

**Comment by empiredan** [comment]
> > > > > > Good enhancement~
> > > > > > I have some questions about updating table replica count:
> > > > > > 
> > > > > > 1. There're also cluster-level config called `max_replica_count`, will it be confict if cluster `max_replica_count` is not equal to table `max_replica_count`? Will important features work such as user read/write, learn, load balance, rolling_update?
> > > > > > 2. Table `app_info` file will store in each replica disk (_dir/.app_info), if `max_replica_count` is updated, this file should also be updated, how to update it?
> > > > > > 3. In your description, `cure` (executed each 10s) will delete redunant replica or add lacking replica. Could you please add some manual test results?
> > > > > > 
> > > > > > Expecting your reply~
> > > > > 
> > > > > 
> > > > > Ok, let's discuss one by one:
> > > > > 
> > > > > 1. Does cluster-level config mean `max_allowed_replica_count` in [feat: restrict the replication factor while creating app XiaoMi/rdsn#963](https://github.com/XiaoMi/rdsn/pull/963) ? Actually `max_replica_count` is the RF, and `max_allowed_replica_count` is a the upper bound to which an RF can be set. Or we should rename `max_replica_count` as replication_factor to avoid misunderstanding ?
> > > > > 2. Good question ! This implementation has't written into `.app_info`, this is a bug ! To guarantee the atomicity, I think first the request `set_replica_count` can be replicated to each replica; Received the request, each replica writes it into `slog`, and then writes the new `max_replica_count` into `.app_info`. Even if a replica server fails during the process, the request will not be lost.
> > > > > 3. As is described in this issue, increasing `max_replica_count` has been tested sufficiently, however decreasing `max_replica_count` has not been tested. I'll test decreasing later to see if redundant replica can be processed correctly.
> > > > 
> > > > 
> > > > Thanks for your reply~ Continue to discuss:
> > > > 
> > > > 1. I mean meta option called `max_replicas_in_group` , you can reference it here:
> > > >    https://github.com/XiaoMi/rdsn/blob/289eb4609ae781e3bcc6bbc6bfeae64dfd8fa785/src/meta/meta_options.cpp#L160-L161
> > > > 2. I suggest that you can update `max_replica_count` through `on_config_sync` into `.app_info`
> > > > 3. I think decreasing replica count may have some problems, expecting your test result~
> > > 
> > > 
> > > Thanks for suggestion !
> > > 
> > > 1. I think we can eliminate `max_replicas_in_group` and turn to partition-level `max_replica_count`. I'll explain this as below:
> > > 
> > > Now `max_replicas_in_group` is only used to update `config_context::MAX_REPLICA_COUNT_IN_GRROUP`; And `config_context::MAX_REPLICA_COUNT_IN_GRROUP` is only used in:
> > > ```c++
> > > void config_context::check_size()
> > > {
> > >     // when add learner, it is possible that replica_count > max_replica_count, so we
> > >     // need to remove things from dropped only when it's not empty.
> > >     while (replica_count(*config_owner) + dropped.size() > MAX_REPLICA_COUNT_IN_GRROUP &&
> > >            !dropped.empty()) {
> > >         dropped.erase(dropped.begin());
> > >         prefered_dropped = (int)dropped.size() - 1;
> > >     }
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > However, `MAX_REPLICA_COUNT_IN_GRROUP` can be replaced with partition-level `max_replica_count` as below:
> > > ```c++
> > > void config_context::check_size()
> > > {
> > >     // when add learner, it is possible that replica_count > max_replica_count, so we
> > >     // need to remove things from dropped only when it's not empty.
> > >     while (replica_count(*config_owner) + dropped.size() > config_owner->max_replica_count &&
> > >            !dropped.empty()) {
> > >         dropped.erase(dropped.begin());
> > >         prefered_dropped = (int)dropped.size() - 1;
> > >     }
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > The `partition_configuration` pointed by `config_owner` is updated in `server_state::on_update_configuration_on_remote_reply`, which will be called by `set_replica_count`.
> > > 
> > > 2. Good idea ! Each `config_sync_interval_ms` (typically 30 ms) the replica server requests `query_configuration_by_node` to the meta server; Received the response, if the ballot of the response is newer than the local, the replica server will update every table-level and partition-level `max_replica_count` to the one of the response. Is it right ?
> > > 3. Actually decreasing replica count has been forbidden till now by us. Decreasing is more error-prone than increasing. If we decide to support decreasing replica count, I'll test sufficiently.
> > 
> > 
> > Thanks for your reply~
> > 
> > 1. If you have already checked that table level replica_count can replace cluster `max_replicas_in_group`, just go ahead~
> > 2. Yes, I recommend update `.app_info` file through `on_config_sync` rpc
> > 3. Okay. How about update this issue title from `update the replication factor` into `increase the replication factor`? As the decreasing is not supported.
> 
> Ok, we can first support increasing the replication factor. Decreasing can be supported later if needed.

Now our implementation has supported to decrease the replication factor. 

It is noticeable that the redundant replica data will be garbage-collected only when meta level is lively, which means `set_meta_level lively` should be executed.
