### ISSUE TITLE
Server 2.0+ using much more network and disk bandwidths

### ISSUE THREAD

**Issue by hycdong** [apache/incubator-pegasus#866]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

2. What did you expect to see?

3. What did you see instead?

4. What version of Pegasus are you using?

**Comment by padmejin** [comment]
1. What did you do?
Recently we were trying to upgrade pegasus from 1.12.3 to 2.0, then upgrade to latest version 2.3. We did some performance tests by making request to clusters with different backend version, and then compared all the metrics between two clusters. We found that pegasus 2.0 are using much more network/disk bandwidths than pegasus 1.12.3.

Eventually we narrowed down the problem to a typical case: when we were sending all write requests to a cluster with only one table that only contained one partition and 3 replications, it was obvious that on the host where the primary replica was stored, the upstream bandwidth is much greater than the downstream bandwidth.

2. What did you expect to see?
On the host where the primary replica was stored, the upstream bandwidths should be at most 2 times larger than the downstream bandwidth.

3. What did you see instead?
 the upstream bandwidths is about 5 to 10 times larger than the downstream bandwidth.

4. What version of Pegasus are you using?
pegasus 2.0
