### ISSUE TITLE
Bug: `.init-info` file lost on server with XFS file system after power failure and reboot

### ISSUE THREAD

**Issue by acelyc111** [apache/incubator-pegasus#879]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
- create a table in a cluster, and write some data, check these data is readable
- power off suddenly
- reboot the servers
- check these data again, some data will be lost

2. What did you expect to see?
no data lost

3. What did you see instead?
some data lost
```
XFS has a dedicated sysctl variable for setting the writeback interval with a default value of 3000.
Warning: While larger values may increase performance, they also increase the severity of data loss caused by a power outage.
```
https://wiki.archlinux.org/title/XFS#Sync_interval

4. What version of Pegasus are you using?
1.12.3 (new versions have the same problem)

**Comment by Smityz** [comment]
What are the symptoms of a cluster losing data? Partitions are healthy but data loss?
