### ISSUE TITLE
有没有编译好的发布包提供啊，自己编译实在太痛苦了，求一个可用的release包

### ISSUE THREAD

**Issue by mabohao1991** [apache/incubator-pegasus#915]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by levy5307** [comment]
You can take a look at this [page](https://github.com/apache/incubator-pegasus/releases)

**Comment by mabohao1991** [comment]
> 你可以看看这个[页面](https://github.com/apache/incubator-pegasus/releases)

您好，这个页面我在手册里面看到了，但是没有找到编译好的包下载链接，能帮忙再给下提示吗？多谢了

**Comment by levy5307** [comment]
> > 你可以看看这个[页面](https://github.com/apache/incubator-pegasus/releases)
> 
> 您好，这个页面我在手册里面看到了，但是没有找到编译好的包下载链接，能帮忙再给下提示吗？多谢了

你往下翻就行，在2.0.0里面有编译好的包，后面的版本确实没有。不过编译好的包，在你们的平台上不一定能跑的通啊，可能会有兼容性问题的 : (

**Comment by levy5307** [comment]
> > 你可以看看这个[页面](https://github.com/apache/incubator-pegasus/releases)
> 
> 您好，这个页面我在手册里面看到了，但是没有找到编译好的包下载链接，能帮忙再给下提示吗？多谢了

你们这边是公司要用Pegasus，还是个人感兴趣玩一下？

**Comment by mabohao1991** [comment]
> 

我们公司也在用Pegasus做的二次开发，我自己想弄个原生的玩一下，顺便看看代码，但是我2.1.0在docker里面没有编译通过，所以就想弄一个编好的版本，跑一下子

**Comment by mabohao1991** [comment]
> > > 你可以看看这个[页面](https://github.com/apache/incubator-pegasus/releases)
> > 
> > 
> > 您好，这个页面我在手册里面看到了，但是没有找到编译好的包下载链接，能帮忙再给下提示吗？多谢了
> 
> 你往下翻就行，在2.0.0里面有编译好的包，后面的版本确实没有。不过编译好的包，在你们的平台上不一定能跑的通啊，可能会有兼容性问题的 : (

我想问一下，这个包适用哪些平台啊，或者有docker镜像吗？

**Comment by levy5307** [comment]
> > > > 你可以看看这个[页面](https://github.com/apache/incubator-pegasus/releases)
> > > 
> > > 
> > > 您好，这个页面我在手册里面看到了，但是没有找到编译好的包下载链接，能帮忙再给下提示吗？多谢了
> > 
> > 
> > 你往下翻就行，在2.0.0里面有编译好的包，后面的版本确实没有。不过编译好的包，在你们的平台上不一定能跑的通啊，可能会有兼容性问题的 : (
> 
> 我想问一下，这个包适用哪些平台啊，或者有docker镜像吗？

@Shuo-Jia @hycdong 你们跟一下这个问题吧

**Comment by hycdong** [comment]
https://pegasus.apache.org/docs/build/compile-by-docker/
https://github.com/pegasus-kv/pegasus-docker/tree/2.1.0/pegasus-build-env
可以参照这两个试试在docker上编译2.1.0

**Comment by levy5307** [comment]
> > 
> 
> 我们公司也在用Pegasus做的二次开发，我自己想弄个原生的玩一下，顺便看看代码，但是我2.1.0在docker里面没有编译通过，所以就想弄一个编好的版本，跑一下子

请问你们这边是哪个公司？目前已经上线Pegasus了吗？

**Comment by levy5307** [comment]
我微信号18500688786，方便的话可以加一下我 : )
