### ISSUE TITLE
We need a faster way to copy

### ISSUE THREAD

**Issue by Arsenal821** [apache/incubator-pegasus#923]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Our business use copy_data frequently， but it's performance is not good. I want improve it

**Describe the feature you'd like:**

I find we can use async_multi_set improve it when single hash_key have multi data. Let's do it.

**Comment by acelyc111** [comment]
@neverchanje 
In some usage scenario, Pegasus users use the Shell tool to copy data from one cluster/table to another to increase partition count in lower version of Pegasus, copy files would not help.
