### ISSUE TITLE
Feature: creat new app through new client interface 

### ISSUE THREAD

**Issue by cauchy1988** [apache/incubator-pegasus#924]
## Feature Request
we are thinking bout adding a new client interface (mainly in java client  ) which can create a new app through only rpc request to the server side~

**Is your feature request related to a problem? Please describe:**

our customer code will run in docker or one of some container type in k8s in the future,  in the container circumstance, customer code can not conveniently use the shell tool------"run.sh" to create a new pegasus app; 

**Describe the feature you'd like:**

we want to realize a client interface which can create a new app through only rpc requests to the server side

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by GiantKing** [comment]
Get/put etc. are business flow, but create/delete apps are management flow. I think mixed two flow together into client is not a good idea. We can't implement authentication in client, which is a basicly requirement for management flow.

**Comment by cauchy1988** [comment]
> Get/put etc. are business flow, but create/delete apps are management flow. I think mixed two flow together into client is not a good idea. We can't implement authentication in client, which is a basicly requirement for management flow.

I think client side can contain not only normal put/get, read/write functionality, but also can include some "tools like" interface for "management usage"  you have mentioned;  authentication is another topic,  since normal read or write also need it;

**Comment by GiantKing** [comment]
> > Get/put etc. are business flow, but create/delete apps are management flow. I think mixed two flow together into client is not a good idea. We can't implement authentication in client, which is a basicly requirement for management flow.
> 
> I think client side can contain not only normal put/get, read/write functionality, but also can include some "tools like" interface for "management usage" you have mentioned; authentication is another topic, since normal read or write also need it;

How to prevent common users from calling this interface? In most scenarios, only administrators have permission to create creat a new app.

**Comment by cauchy1988** [comment]
> > > Get/put etc. are business flow, but create/delete apps are management flow. I think mixed two flow together into client is not a good idea. We can't implement authentication in client, which is a basicly requirement for management flow.
> > 
> > 
> > I think client side can contain not only normal put/get, read/write functionality, but also can include some "tools like" interface for "management usage" you have mentioned; authentication is another topic, since normal read or write also need it;
> 
> How to prevent common users from calling this interface? In most scenarios, only administrators have permission to create creat a new app.

previously, we also cannot limit  permissions of normal users to create a app, since they can also use the shell tools;  In this case, I will add kerberos to the related rpc interface to let only the administrators to create new app;

**Comment by acelyc111** [comment]
Thanks to @GiantKing 's reminding, we should keep in mind not expose too many privilege to common Pegasus users.
But I also think we should achieve the goal by using authority control mechanism in Pegasus, not to provide Java API is not reasonable cause any body can use the shell tool to create table now, without any permission.

**Comment by levy5307** [comment]
I think it's OK to add `createTable` interface . Many other storage systems support this interface, for example: Dynamo. And Here is the [official document](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/dynamodb/DynamoDbClient.html#createTable-java.util.function.Consumer-)
And In my opinion, it's better to enable authentation to ensure safety.
